### ISSUE TITLE
neko HTMLScanner java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by jeffcjohnson** [HtmlUnit/htmlunit#126]
Many websites that I crawl are now failing with HtmlUnit 2.37.0 with the following error:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$CurrentEntity.read(HTMLScanner.java:1901) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:3075) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2900) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2747) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2127) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394) ~[neko-htmlunit-2.37.0.jar:2.37.0]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.12.0.jar:?]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:758) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:553) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:419) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:336) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:488) ~[htmlunit-2.37.0.jar:2.37.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:469) ~[htmlunit-2.37.0.jar:2.37.0]
```

**Comment by jeffcjohnson** [comment]
Just saw it was already fixed in neko.
https://github.com/HtmlUnit/htmlunit-neko/issues/5

**Comment by rbri** [comment]
Will try to make a new HtmlUnit release soon - maybe at the end of Feb.
So far you can switch to the latest SNAPSHOT or only switch to the latest Neko Snapshot build.

**Comment by jeffcjohnson** [comment]
I was able to use the snapshot and the problem was fixed.  Thanks so much!

For anyone wanting to use snapshots, you can add the repo to your gradle file like this:

```
repositories {
    maven {
        // For "net.sourceforge.htmlunit:htmlunit:2.38.0-SNAPSHOT"
        url "https://oss.sonatype.org/service/local/repositories/snapshots/content/"
    }
}
```
