### ISSUE TITLE
NullPointerException in handleJavaScriptException

### ISSUE THREAD

**Issue by jeffcjohnson** [HtmlUnit/htmlunit#136]
I get the following NPE with HtmlUnit.  I'm hoping the fix will be obvious to someone that knows the code well.  If not I can try to come up with a way to reproduce it.

Thanks!

```
2020-02-17 15:29:15,504 ERROR [com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl] Job run failed with unexpected RuntimeException: null
java.lang.NullPointerException: null
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.handleJavaScriptException(JavaScriptEngine.java:984) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:886) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624) ~[htmlunit-core-js-2.37.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537) ~[htmlunit-core-js-2.37.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:815) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.setState(XMLHttpRequest.java:211) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.doSend(XMLHttpRequest.java:785) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.access$000(XMLHttpRequest.java:103) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest$1.run(XMLHttpRequest.java:634) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624) ~[htmlunit-core-js-2.37.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537) ~[htmlunit-core-js-2.37.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.background.JavascriptXMLHttpRequestJob.run(JavascriptXMLHttpRequestJob.java:36) ~[htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424) [htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148) [htmlunit-2.38.0-SNAPSHOT.jar:2.38.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

```

**Comment by rbri** [comment]
From a first look into the code this look strange. Is there any more in the log? Looks like the webClient is null....

**Comment by jeffcjohnson** [comment]
That's the only log message I see.  It happens sporadically from the same page.  I assume it is some sort of timing issue with the javascript running in the background.

**Comment by rbri** [comment]
Ok, looks like i have to polish my crystal ball - will inform if i have a new working snapshot that
* fixes this or
* has some more logging to give me a hint

**Comment by jeffcjohnson** [comment]
I had some other sites fail sporadically with page.getFirstByXPath() when Javascript was enabled until I put a Thread.sleep(1000) right after getPage().

It seems like there are a few other issues related to fully loading the page with regards to Javascript that if fixed might fix this issue.

**Comment by jeffcjohnson** [comment]
After adding `webClient.setAjaxController(new NicelyResynchronizingAjaxController());` to my code things starting working much better.

**Comment by rbri** [comment]
>After adding `webClient.setAjaxController(new
>NicelyResynchronizingAjaxController());` to my code things starting
>working much better

Sounds like an hint....

**Comment by rbri** [comment]
Sorry, was busy with other issues. Will work on this during the next days.

**Comment by rbri** [comment]
Sorry for the delay, but....
Think i have found the reason (and a solution) for your problem.
Will make a new snapshot build later today (please check https://twitter.com/HtmlUnit for details).

Please try and inform about your results.

**Comment by jeffcjohnson** [comment]
I just tried with 2.39.0 and it fails unless I add `webClient.ajaxController = NicelyResynchronizingAjaxController()`.

Because it fails in a background thread and is a timing problem, I can't use a debugger to find the problem as the debugger adds enough delay for the javascript to finish loading (or whatever it is doing).   Even putting in a few print lines to find the line in my code that fails will cause enough delay for it to work.

**Comment by rbri** [comment]
Too bad,
can you please attach the current stack trace.

**Comment by jeffcjohnson** [comment]
These are two different stack traces that occur, I hope this is helpful:

```
2020-04-06 10:51:34,357 ERROR [com.gargoylesoftware.htmlunit.WebClient] Exception while closing a topLevelWindow
java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage' 

[SNIP]

	at com.gargoylesoftware.htmlunit.html.DomNode.getScriptableObject(DomNode.java:945) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.host.event.Event.<init>(Event.java:217) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.host.event.BeforeUnloadEvent.<init>(BeforeUnloadEvent.java:71) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1227) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.isOnbeforeunloadAccepted(HtmlPage.java:1301) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.TopLevelWindow.close(TopLevelWindow.java:115) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.WebClient.close(WebClient.java:1979) [htmlunit-2.39.0.jar:2.39.0]
	at helix.extractor.core.WebClientExtractor.close(WebClientExtractor.kt:52) [main/:?]
	at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:59) [kotlin-stdlib-jdk7-1.3.61.jar:1.3.61-release-180 (1.3.61)]
	at helix.extractor.core.Extractor.extract(Extractor.kt:28) [main/:?]
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt.main(WellsFargoExtractor.kt:168) [main/:?]
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt.main(WellsFargoExtractor.kt) [main/:?]
Exception in thread "main" ======= EXCEPTION START ========
Exception class=[java.lang.RuntimeException]
com.gargoylesoftware.htmlunit.ScriptException: Exception invoking getLength
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:891)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:820)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:792)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2567)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2560)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.lambda$executeEventHandlersIfNeeded$0(HtmlPage.java:1250)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1250)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.cleanUp(HtmlPage.java:332)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:550)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:420)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:337)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:489)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:470)
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt$extractRecordsForState$1.invokeSuspend(WellsFargoExtractor.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.SequenceBuilderIterator.yieldAll(SequenceBuilder.kt:183)
	at kotlin.sequences.SequenceScope.yieldAll(SequenceBuilder.kt:100)
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt$extractRecords$1.invokeSuspend(WellsFargoExtractor.kt:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:374)
	at helix.extractor.util.JsonKt.printJsonPretty(json.kt:22)
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt$main$1.invoke(WellsFargoExtractor.kt:171)
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt$main$1.invoke(WellsFargoExtractor.kt)
	at helix.extractor.core.Extractor.extract(Extractor.kt:30)
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt.main(WellsFargoExtractor.kt:168)
	at helix.extractor.extractors.wellsfargo.WellsFargoExtractorKt.main(WellsFargoExtractor.kt)
Caused by: java.lang.RuntimeException: Exception invoking getLength
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:214)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject$GetterSlot.getValue(ScriptableObject.java:348)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.get(ScriptableObject.java:475)
	at com.gargoylesoftware.htmlunit.javascript.SimpleScriptable.get(SimpleScriptable.java:79)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.getProperty(ScriptableObject.java:2340)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getObjectPropNoWarn(ScriptRuntime.java:1615)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1430)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:340)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3607)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:813)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876)
	... 36 more
Caused by: java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage'
```

```
2020-04-06 10:45:22,017 ERROR [com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl] Job run failed with unexpected RuntimeException: Exception invoking setHref
com.gargoylesoftware.htmlunit.ScriptException: Exception invoking setHref
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:891) ~[htmlunit-2.39.0.jar:2.39.0]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537) ~[htmlunit-core-js-2.39.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:820) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.setState(XMLHttpRequest.java:214) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.doSend(XMLHttpRequest.java:805) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.access$000(XMLHttpRequest.java:106) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest$1.run(XMLHttpRequest.java:637) ~[htmlunit-2.39.0.jar:2.39.0]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537) ~[htmlunit-core-js-2.39.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.background.JavascriptXMLHttpRequestJob.run(JavascriptXMLHttpRequestJob.java:36) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424) [htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148) [htmlunit-2.39.0.jar:2.39.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.RuntimeException: Exception invoking setHref
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:214) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject$GetterSlot.setValue(ScriptableObject.java:323) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.putImpl(ScriptableObject.java:2846) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.put(ScriptableObject.java:533) ~[htmlunit-core-js-2.39.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitScriptable.put(HtmlUnitScriptable.java:151) ~[htmlunit-2.39.0.jar:2.39.0]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.putProperty(ScriptableObject.java:2527) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1740) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1734) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1447) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111) ~[htmlunit-core-js-2.39.0.jar:?]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427) ~[htmlunit-core-js-2.39.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:340) ~[htmlunit-2.39.0.jar:2.39.0]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3607) ~[htmlunit-core-js-2.39.0.jar:?]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:813) ~[htmlunit-2.39.0.jar:2.39.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876) ~[htmlunit-2.39.0.jar:2.39.0]
	... 14 more
Caused by: java.lang.IllegalStateException: No script object associated with the Page. class: 'com.gargoylesoftware.htmlunit.html.HtmlPage'

[SNIP]

```

**Comment by rbri** [comment]
Hopefully the 'No script object associated with the Page' issue is fixed now. Please check with the latest snapshot.

**Comment by rbri** [comment]
i guess this is fixed
