### ISSUE TITLE
net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot find function matchMedia in object

### ISSUE THREAD

**Issue by sthirumu** [HtmlUnit/htmlunit#137]
I am trying to login by clicking a button and it gives me this error.The resultpage is a javascript page instead of a page that is shown after login is cliked.

**Comment by rbri** [comment]
Can you please post the whole stack trace

**Comment by sthirumu** [comment]
Enclosed exception: 
net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot find function matchMedia in object [object]. (script in https://<host>:<port>/oamconsole/ from (1, 34) to (68, 10)#2)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3651)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3629)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3657)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3676)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3740)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2249)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2216)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1501)
	at script(script in https://host:port/oamconsole/ from (1, 34) to (68, 10):2)
	at script(script in https://host:port/oamconsole/ from (1, 34) to (68, 10):5)
	at script(script in https://host:port/oamconsole/ from (1, 34) to (68, 10):8)
	at script(script in https://host:port/oamconsole/ from (1, 34) to (68, 10):19)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:845)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:263)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3058)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$5.doRun(JavaScriptEngine.java:415)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:520)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:529)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:536)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:424)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:399)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptIfPossible(HtmlPage.java:899)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeInlineScriptIfNeeded(HtmlScript.java:309)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:364)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$1.execute(HtmlScript.java:213)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:238)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:690)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:648)
	at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1132)
	at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1034)
	at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
	at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:329)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3058)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:1994)
	at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:907)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:892)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:350)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:304)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:134)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:101)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:447)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:330)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:355)
	at com.gargoylesoftware.htmlunit.html.HtmlForm.submit(HtmlForm.java:187)
	at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLFormElement$2.execute(HTMLFormElement.java:257)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.processPostponedActions(JavaScriptEngine.java:552)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:485)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$6.doRun(JavaScriptEngine.java:449)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:520)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:529)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:536)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:456)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunctionIfPossible(HtmlPage.java:925)
	at com.gargoylesoftware.htmlunit.javascript.host.EventListenersContainer.executeEventHandler(EventListenersContainer.java:182)
	at com.gargoylesoftware.htmlunit.javascript.host.EventListenersContainer.executeBubblingListeners(EventListenersContainer.java:200)
	at com.gargoylesoftware.htmlunit.javascript.host.Node.fireEvent(Node.java:609)
	at com.gargoylesoftware.htmlunit.html.HtmlElement$2.run(HtmlElement.java:886)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:529)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:536)
	at com.gargoylesoftware.htmlunit.html.HtmlElement.fireEvent(HtmlElement.java:891)
	at com.gargoylesoftware.htmlunit.html.HtmlElement.click(HtmlElement.java:1237)
	at com.gargoylesoftware.htmlunit.html.HtmlElement.click(HtmlElement.java:1208)
	at com.gargoylesoftware.htmlunit.html.HtmlElement.click(HtmlElement.java:1177)
	at webcli.t2.main(t2.java:59)

**Comment by rbri** [comment]
The function window.matchMedia (https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) is supported by HtmlUnit.

What HtmlUnit version do you use? Can you please have a look on the failing script code and provide some more details.

**Comment by rbri** [comment]
Without having at least the source code of the script i can't do anything. Will close this for now. Please open a new issue if you still have this problem and provide more details.
