### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by Shouheng88** [HtmlUnit/htmlunit#15]
```java
Exception in thread "main" java.lang.StackOverflowError
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
...
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit_r(NodeTransformer.java:439)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transformCompilationUnit(NodeTransformer.java:69)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transform(NodeTransformer.java:47)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transform(NodeTransformer.java:50)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transform(NodeTransformer.java:50)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transform(NodeTransformer.java:50)
	at net.sourceforge.htmlunit.corejs.javascript.NodeTransformer.transform(NodeTransformer.java:35)
	at net.sourceforge.htmlunit.corejs.javascript.CodeGenerator.compile(CodeGenerator.java:65)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.compile(Interpreter.java:382)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2631)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1587)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:216)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1576)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:714)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:877)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:616)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:532)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:723)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:689)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:104)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1088)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:975)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:371)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:246)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:267)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:802)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:758)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1236)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1136)
	at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:226)
	at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:345)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3189)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2141)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:945)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:521)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:472)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:1001)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:250)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:196)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:267)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:158)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:532)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:399)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:316)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:467)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:449)
```

**Comment by rbri** [comment]
net.sourceforge.htmlunit.corejs is more or less our slightly patched version of Rhino. This looks like a bug there but without a simple js that reproduces the error i see no chance to address this.

**Comment by Shouheng88** [comment]
Thanks for your reply. You can try to reproduce this error by the code below,
```java
        WebClient webClient = new WebClient(BrowserVersion.CHROME);
        webClient.getOptions().setJavaScriptEnabled(true);   
        webClient.getOptions().setCssEnabled(false); 
        webClient.getOptions().setThrowExceptionOnScriptError(false); 
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
        webClient.getOptions().setTimeout(10 * 1000); 
        webClient.waitForBackgroundJavaScript(30 * 1000); 
        HtmlPage page = webClient.getPage("https://leetcode.com/problems/distribute-coins-in-binary-tree/");

        String html = page.asXml();
        System.out.println(html);
```

**Comment by rbri** [comment]
Have done a test with this and the latest sources. Got a js error and made a fix for the error. Usually this gets merged into rhino in 1 week. Will then try to come back to this issue.

https://github.com/mozilla/rhino/pull/530

**Comment by rbri** [comment]
Finally got this page working but this requires another rhino fix. Will require some time to build a test case for this.

**Comment by rbri** [comment]
still waiting for the rhino fix - sorry

**Comment by rbri** [comment]
Sorry for being that late, this should work now with the latest snapshot.

**Comment by Shouheng88** [comment]
thanks for your replay, i will try it
