### ISSUE TITLE
Property already defined in this object literal

### ISSUE THREAD

**Issue by DSantiagoBC** [HtmlUnit/htmlunit#176]
I'm trying to load [this link](http://servicios.supersociedades.gov.co/barandavirtual/#!/app/estados) using HtmlUnit to fill the form and get some data, but the returned page is empty. This is the code I'm using:

```java
try (WebClient client = new WebClient(BrowserVersion.FIREFOX)) {
    client.getOptions().setThrowExceptionOnScriptError(false);
    HtmlPage page = client.getPage("http://servicios.supersociedades.gov.co/barandavirtual/#!/app/estados");
    client.waitForBackgroundJavaScript(10000);
    System.out.println(page.asXml());
}
```

When ```getPage``` returns, I can see just some scripts, and none of the visible content of the page. I get a couple of exceptions

<details>
    <summary>Stack trace</summary>

```
Exception in thread "main" ======= EXCEPTION START ========
Exception class=[net.sourceforge.htmlunit.corejs.javascript.EvaluatorException]
com.gargoylesoftware.htmlunit.ScriptException: Property "sitekeyDev" already defined in this object literal. (http://servicios.supersociedades.gov.co/barandavirtual/app/js/app.js#2981)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:891)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:722)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:688)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:103)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1117)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:997)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:361)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:234)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:256)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:560)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:514)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1192)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1132)
	at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:219)
	at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:312)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3189)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2114)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:760)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:638)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:451)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:368)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:520)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:501)
	at co.com.slt.prubas.htmlunit.Main.main(Main.java:24)
Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: Property "sitekeyDev" already defined in this object literal. (http://servicios.supersociedades.gov.co/barandavirtual/app/js/app.js#2981)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:438)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:258)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:234)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.objectLiteral(Parser.java:3619)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3119)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2743)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.argumentList(Parser.java:2710)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExprTail(Parser.java:2860)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2779)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.nameOrLabel(Parser.java:2063)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1263)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statement(Parser.java:1127)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parseFunctionBody(Parser.java:764)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.function(Parser.java:934)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3111)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2743)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parenExpr(Parser.java:3216)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3127)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2743)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1273)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statement(Parser.java:1127)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:664)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:583)
	at net.sourceforge.htmlunit.corejs.javascript.Context.parse(Context.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2586)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1590)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:224)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1579)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:713)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876)
	... 35 more
Enclosed exception: 
net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: Property "sitekeyDev" already defined in this object literal. (http://servicios.supersociedades.gov.co/barandavirtual/app/js/app.js#2981)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:438)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:258)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:234)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.objectLiteral(Parser.java:3619)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3119)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2743)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.argumentList(Parser.java:2710)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExprTail(Parser.java:2860)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2779)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.nameOrLabel(Parser.java:2063)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1263)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statement(Parser.java:1127)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parseFunctionBody(Parser.java:764)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.function(Parser.java:934)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3111)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2743)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parenExpr(Parser.java:3216)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3127)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2743)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2558)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2542)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2498)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2470)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2459)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2448)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2437)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2415)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2379)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2335)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1273)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statement(Parser.java:1127)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:664)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:583)
	at net.sourceforge.htmlunit.corejs.javascript.Context.parse(Context.java:2637)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2586)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1590)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:224)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1579)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:713)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:722)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:688)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:103)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1117)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:997)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:361)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:234)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:256)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:560)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:514)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1192)
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1132)
	at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:219)
	at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:312)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3189)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2114)
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443)
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:760)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236)
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:638)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:451)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:368)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:520)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:501)
	at co.com.slt.prubas.htmlunit.Main.main(Main.java:24)
```
</details>

I found the problem is in one the javascripts. There's an object literal which is being declared using the same property name twice.

I downloaded the script, commented out the second parameter usage and used Charles to execute the modified script. Now it works like a charm

I think duplicated keys for object literals should not cause errors, as "real" browsers simply ignore the second assignment

I'm sorry if I didn't explain myself correctly, but I'm new to github and as you may have noticed english is not my first language. I'm looking forward to answer any questions!

**Comment by RuralHunter** [comment]
Hi, you'd better provide a simple code snippet to reproduce the problem, so that the developers can track the problem quickly. It can be like this: #174

**Comment by rbri** [comment]
see #755

**Comment by rbri** [comment]
Rhino has a fix for this (now) - https://github.com/mozilla/rhino/pull/2073

Fix is merged - 4.17.0 fixes this.
