### ISSUE TITLE
Exception invoking getImageData

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#178]
Hey @rbri :)

I suddenly see tons of these popping up:

```
ERROR  [15:19:43.997]  Error during JavaScript execution
com.gargoylesoftware.htmlunit.ScriptException: Exception invoking getImageData
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:891)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:820)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:792)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2601)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2594)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptFunctionJob.runJavaScript(JavaScriptFunctionJob.java:57)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptExecutionJob.run(JavaScriptExecutionJob.java:102)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:429)
        at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Exception invoking getImageData
        at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:214)
        at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:457)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1674)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:340)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3607)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:813)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876)
        ... 12 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
        at sun.awt.image.IntegerInterleavedRaster.getDataElements(IntegerInterleavedRaster.java:219)
        at java.awt.image.BufferedImage.getRGB(BufferedImage.java:917)
        at com.gargoylesoftware.htmlunit.javascript.host.canvas.rendering.AwtRenderingBackend.getBytes(AwtRenderingBackend.java:499)
        at com.gargoylesoftware.htmlunit.javascript.host.canvas.ImageData.<init>(ImageData.java:124)
        at com.gargoylesoftware.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.getImageData(CanvasRenderingContext2D.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:188)
        ... 21 common frames omitted
ERROR  [15:19:43.997]  Job run failed with unexpected RuntimeException: Exception invoking getImageData
com.gargoylesoftware.htmlunit.ScriptException: Exception invoking getImageData
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:891)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:820)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:792)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2601)
        at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2594)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptFunctionJob.runJavaScript(JavaScriptFunctionJob.java:57)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptExecutionJob.run(JavaScriptExecutionJob.java:102)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:429)
        at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148)
        at java.lang.Thread.run(Thread.java:748)
```

This must be something internal. I don't recall having seen `getImageData()` anywhere.  
HtmlUnit `2.40.0`, nothing fancy. Sadly, again, it's an internal page which I cannot provide.

I don't have time to dig deeper atm and I'll be on vacation for the next couple of weeks but maybe the trace is already enough to pin the issue down.

**Comment by rbri** [comment]
Hi, looks like i'm able to  fix this without any further information.

**Comment by rbri** [comment]
Fixed, thanks.

**Comment by black-snow** [comment]
@rbri awesome! Do you have a link where I can buy you a coffe? :)
