### ISSUE TITLE
Memory leak in 2.41.0

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#185]
Hey Ron,

there seems to be a memory leak in 2.41.0. Since I upgraded my JVM constantly runs OOM. Happens on prod (Debian) as well as on my local WSL 2 Ubuntu. Same build runs as expected just by switching back to 2.40.0.
I'll see if I can get a dump.

Cheers

**Comment by black-snow** [comment]
Here's one trace that might help:

```
Exception in thread "JS executor for com.gargoylesoftware.htmlunit.WebClient@d108406" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at net.sourceforge.htmlunit.corejs.javascript.EmbeddedSlotMap.createSlot(EmbeddedSlotMap.java:241)
        at net.sourceforge.htmlunit.corejs.javascript.EmbeddedSlotMap.get(EmbeddedSlotMap.java:157)
        at net.sourceforge.htmlunit.corejs.javascript.SlotMapContainer.get(SlotMapContainer.java:60)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.putImpl(ScriptableObject.java:2861)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.put(ScriptableObject.java:536)
        at net.sourceforge.htmlunit.corejs.javascript.IdScriptableObject.put(IdScriptableObject.java:479)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.readObject(JsonParser.java:123)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.readValue(JsonParser.java:58)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.readArray(JsonParser.java:167)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.readValue(JsonParser.java:60)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.readObject(JsonParser.java:119)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.readValue(JsonParser.java:58)
        at net.sourceforge.htmlunit.corejs.javascript.json.JsonParser.parseValue(JsonParser.java:44)
        at net.sourceforge.htmlunit.corejs.javascript.NativeJSON.parse(NativeJSON.java:109)
        at net.sourceforge.htmlunit.corejs.javascript.NativeJSON.execIdCall(NativeJSON.java:88)
        at net.sourceforge.htmlunit.corejs.javascript.IdFunctionObject.call(IdFunctionObject.java:100)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1674)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1009)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:340)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3629)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:813)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876)
        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:624)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354)
        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:820)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.setState(XMLHttpRequest.java:214)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.doSend(XMLHttpRequest.java:805)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.access$000(XMLHttpRequest.java:106)
        at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest$1.run(XMLHttpRequest.java:637)
```

**Comment by black-snow** [comment]
```
One instance of "com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl" loaded by "sun.misc.Launcher$AppClassLoader @ 0xc0004cd8" occupies 757.376.160 (77,50 %) bytes. The memory is accumulated in one instance of "java.lang.Object[]" loaded by "<system class loader>".

Keywords
sun.misc.Launcher$AppClassLoader @ 0xc0004cd8
java.lang.Object[]
com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl
```

3x `JavaScriptFunctionJob` 250 MB each with some huge `byte[]` arrays.

---

```
2.973 instances of "com.gargoylesoftware.htmlunit.html.HtmlTableRow", loaded by "sun.misc.Launcher$AppClassLoader @ 0xc0004cd8" occupy 103.801.216 (10,62 %) bytes. These instances are referenced from one instance of "java.lang.Thread", loaded by "<system class loader>"

Keywords
sun.misc.Launcher$AppClassLoader @ 0xc0004cd8
com.gargoylesoftware.htmlunit.html.HtmlTableRow
java.lang.Thread
```

**Comment by black-snow** [comment]
![oom_dump](https://user-images.githubusercontent.com/579733/86130442-6fd8a400-bae4-11ea-929b-51c842feafd9.png)

**Comment by rbri** [comment]
As always the changes in core-js and/or HtmlUnit might trigger some new source paths leading to new problems.
But it is really hard to guess from the above information what might go wrong.

**Comment by black-snow** [comment]
@rbri is there anything else I can provide?

**Comment by rbri** [comment]
good question: maybe you can try to intercept (Chales WebProxy / Fiddler) the json used in .JsonParser.parseValue(JsonParser.java:44). If parsing shows the problem without the page than i have something to work on....

**Comment by rbri** [comment]
Any news?

**Comment by black-snow** [comment]
Sadly no and no time to investigate this week. :<

**Comment by rbri** [comment]
No problem, bithub will wake me up as soon you provide some more details.

**Comment by black-snow** [comment]
Moved to 2.44 snapshot - if I can't spot any leakage there I'll close this thing.

**Comment by rbri** [comment]
will close this for now, please open a new one if you face the problem again (or another one :-))

**Comment by black-snow** [comment]
yup, thanks
