### ISSUE TITLE
NoSuchFileException on htmlunitXXX.tmp file

### ISSUE THREAD

**Issue by manischau** [HtmlUnit/htmlunit#195]
HtmlLink.cachedWebResponse_ caches a WebResponse, which may hold the downloaded content in a DownloadedContent.OnFile. The same WebResponse may also reside in the Cache. If evicted from the Cache, this invalidates HtmlLink.cachedWebResponse_, because the tmp-file is deleted.

Occurs if the same css-file is loaded again after lots of other web requests that presumably cause the cache eviction.

java.nio.file.NoSuchFileException: /var/folders/4l/5wpxhpr92lvg81kk3jgvbhj00000gn/T/htmlunit308111101111871924.tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_181]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_181]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_181]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_181]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[na:1.8.0_181]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[na:1.8.0_181]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[na:1.8.0_181]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[na:1.8.0_181]
	at com.gargoylesoftware.htmlunit.DownloadedContent$OnFile.getInputStream(DownloadedContent.java:89) ~[htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebResponseData.getStream(WebResponseData.java:98) ~[htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebResponseData.getInputStream(WebResponseData.java:205) ~[htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebResponse.getContentAsStream(WebResponse.java:274) ~[htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.loadStylesheet(CSSStyleSheet.java:337) ~[htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLLinkElement.getSheet(HTMLLinkElement.java:144) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.css.StyleSheetList.item(StyleSheetList.java:190) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.Window.getComputedStyle(Window.java:1786) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.Element.isDisplayNone(Element.java:706) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.html.HTMLElement.getOffsetWidth(HTMLElement.java:1214) [htmlunit-2.42.0.jar:2.42.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:188) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject$GetterSlot.getValue(ScriptableObject.java:348) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.get(ScriptableObject.java:478) [htmlunit-core-js-2.42.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.SimpleScriptable.get(SimpleScriptable.java:79) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.host.Element.get(Element.java:520) [htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.getProperty(ScriptableObject.java:2352) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1605) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1598) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1460) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1013) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:427) [htmlunit-core-js-2.42.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:340) [htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3641) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:123) [htmlunit-core-js-2.42.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$2.doRun(JavaScriptEngine.java:762) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:876) [htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:619) [htmlunit-core-js-2.42.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537) [htmlunit-core-js-2.42.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:354) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:771) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:747) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:738) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScript(HtmlPage.java:943) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeInlineScriptIfNeeded(HtmlScript.java:305) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:395) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:234) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:256) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:560) [htmlunit-2.42.0.jar:2.42.0]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) [xercesImpl-2.12.0.jar:na]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:514) [htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1192) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1132) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:219) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:312) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3189) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2114) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:937) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:443) [neko-htmlunit-2.42.0.jar:2.42.0]
	at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:394) [neko-htmlunit-2.42.0.jar:2.42.0]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) [xercesImpl-2.12.0.jar:na]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:760) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:236) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parseHtml(HtmlUnitNekoHtmlParser.java:179) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:280) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:163) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:638) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:451) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:368) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:520) [htmlunit-2.42.0.jar:2.42.0]
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:501) [htmlunit-2.42.0.jar:2.42.0]

**Comment by rbri** [comment]
Thanks for the report,
you are right, having HtmlLink.cachedWebResponse_ is not the best idea.

Was able to write a unit test to reproduce your case and a fix is on the way.
Please check twitter (https://twitter.com/HtmlUnit) for info about new snapshots.

Thanks
