### ISSUE TITLE
error on javascript containing backtick (`) multi-line string

### ISSUE THREAD

**Issue by refacktor** [HtmlUnit/htmlunit#296]
I'm not sure if this is a bug or a feature request.

Stack Trace:

```
Exception class=[net.sourceforge.htmlunit.corejs.javascript.EvaluatorException]
com.gargoylesoftware.htmlunit.ScriptException: unterminated string literal (http://localhost/agent/clientlibs/scripts/ho
me-table.js#30)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:949)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:619)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:353)

```
The js file it's complaining about looks like this:

```
				render: (data, type, row, meta) => {
					return `<div>                           // <=== this is line 30
			            <i class="user-id">ID: ${row.userId}</i>

                                      ... `; }

```

**Comment by rbri** [comment]
It's both :-)

The reason behind is the internal usage of Rhino and the support for templates is still missing in Rhino (see https://github.com/mozilla/rhino/issues/773)

**Comment by rbri** [comment]
Rhino now supports templates, you can try the latest snapshot or wait for 2.51.0.

**Comment by refacktor** [comment]
Verified in 2.54.0, works fine now.

**Comment by rbri** [comment]
Great thanks for the feedback.
