### ISSUE TITLE
Casting exception HtmlPage

### ISSUE THREAD

**Issue by cesarcastmore** [HtmlUnit/htmlunit#30]
I am trying to get information about items but I have to get this exception. 

`java.lang.ClassCastException: com.gargoylesoftware.htmlunit.TextPage cannot be cast to com.gargoylesoftware.htmlunit.html.HtmlPage
	at com.supermarket.HomeDepot.search(HomeDepot.java:52)
	at com.aws.Configuration.execute(Configuration.java:121)
	at com.stage.api.ms.entity.ComprasTest.method(ComprasTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
out{}`

The website is "https://www.homedepot.com.mx/SearchDisplay?sType=SimpleSearch&resultCatEntryType=2&showResultsPage=true&searchSource=Q&beginIndex=0&pageSize=20&searchTerm=television"

My class is the following:

`package com.supermarket;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import java.net.URLEncoder;

import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlAddress;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import com.gargoylesoftware.htmlunit.TextPage;
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.ThreadedRefreshHandler;

import java.util.List;
import java.math.BigDecimal;

import com.http.Request;
import com.http.Connection;
import com.http.Response;

public class HomeDepot {

	public static String url="https://www.homedepot.com.mx/SearchDisplay?sType=SimpleSearch&resultCatEntryType=2&showResultsPage=true&searchSource=Q&beginIndex=0&pageSize=20&searchTerm=";
	public static String PAGE="https://www.homedepot.com.mx";

	public HomeDepot(){

	}

	public JSONObject search(String searchQuery, Integer pageNum) throws Exception {

		JSONArray listJson = new JSONArray();
		String total ="0";

  		String searchUrl = url  + URLEncoder.encode(searchQuery, "UTF-8") + "&p=" + pageNum;

  		WebClient client = new WebClient(BrowserVersion.FIREFOX_60);  
		client.getOptions().setCssEnabled(false);  
		client.getOptions().setJavaScriptEnabled(false); 
		client.getOptions().setThrowExceptionOnFailingStatusCode(false);

		HtmlPage page= null; 
		try {  
  			System.out.println(searchUrl);

  			page = client.getPage(searchUrl);
		} catch(Exception e){
  			e.printStackTrace();
		}

		
		JSONObject res= new JSONObject();

	

		return res;

	}

	public void addItems(String value, JSONArray lines, HtmlPage page){

		List<?> items = page.getByXPath(value);  
		if(items.isEmpty()){  
  			System.out.println("No items found !");
		}else{
			for(Object  obj : items){  
			  JSONObject itemJson = createItem(obj);
			  lines.add(itemJson);
			}

		}

	}

	public JSONObject createItem(Object  obj){
		HtmlElement htmlItem = (HtmlElement) obj; 
		JSONObject itemJson = new JSONObject();

		System.out.println("HTML" +  htmlItem.asXml());

  		HtmlElement imagenHtml = (HtmlElement) htmlItem.getFirstByXPath(".//img");  
  		String imagen = imagenHtml.getAttribute("src");
		itemJson.put("imagen", imagen);

		return itemJson;
	}

}`

It is strange because I test using postman. I get the code html but I test using CURL, I don't get code html.

**Comment by mguillem** [comment]
HtmlUnit seems to be right here.

The server is sending a response of content type `text/plain` which results in a `TextPage` in HtmlUnit therefore you can't cast it to an `HtmlPage`.

If the server is sending something else back when using postman, then you have to investigate to see what is requested in this case (request url, query & headers) and do the same with HtmlUnit.

**Comment by cesarcastmore** [comment]
Hello @mguillem 

I am reviewing the headers created by my Browser. I have sent all requests using all headers created by Browser. I discovery that the server responses when I use the  "Cookie" header.  An Example is

COOKIE
Store_Defaulted=true; WC_DefaultStore=8702; WC_MarketId=21; WC_PERSISTENT=RV6YU6BeyCJppzUWjJbPaPrAmc0plVSS1OMFoNAwwlY%3D%3B2019-04-07+16%3A37%3A59.19_1554673079104-43582_10351; _gcl_au=1.1.534343239.1554673082;  

I don't have  idea what it is meaning. I have read that this cookie is set to do the web more secure.

Could I make this cookie in html unit? if it is possible, Do you have an example?

**Comment by mguillem** [comment]
You can use HtmlUnit's CookieManager to configure cookies that have to be used upfront:
http://htmlunit.sourceforge.net/apidocs/com/gargoylesoftware/htmlunit/WebClient.html#getCookieManager--

**Comment by rbri** [comment]
In general you have three options:

1. Do the same with HtmlUnit as you have done with your browser (step by step). I guess you have done some steps before your are reaching the search page (maybe a login). Usually cookies are set by the server to track the session. Like a real browser HtmlUnit takes care of the cookie from the server and sends them back if appropriate.
2. Use the Cookie manager and 'inject' the cookie before doing the request
3. Create a WebRequest and set the cookie header on the request. Then call client.getPage(request)

But i fear 2 and 3 will not work because the cookie is not known at the server side and/or outdated.

And finally i like to suggest to use a web proxy like Charles or Fiddler to inspect the traffic from HtmlUnit and your browser to understand what is going on and to be able to compare each other.

**Comment by cesarcastmore** [comment]
Hello @mguillem @rbri  

The cookie has information that I don't know where it is taken. I would like to know how to make this cookie. 

Could you give some suggestions how to make?

**Comment by cesarcastmore** [comment]
Hello @rbri @mguillem 
I am sorry to do some questions. I am beginner developing html unit. I love this library compare to others. 

How could I make or took from the server the cookies?
How could I set my cookie in my request?
Before to send, Do I do some transformations?

**Comment by rbri** [comment]
I like to suggest you to read a good tutorial about cookies first. As next step install Charles or fiddler than start your browser and watch the header for every single step. To have a clear start clear your browses cookie store first.
You will see you browser starts the game with a request and receives a response. At some point the response will contain a set-cookie header and starting with this the client will send the cookie back with every request.
HtmlUnit will do exactly the same there is usually no need to add cookies manually.
