### ISSUE TITLE
JS AudioContext.decodeAudioData

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#33]
I have an issue with a site that's really hard to debug for it sometimes, under certain conditions and if all planets are aligned embeds a live-chat script that throws an JS error with HtmlUnit.
The script requires [decodeAudioData](https://developer.mozilla.org/de/docs/Web/API/AudioContext/decodeAudioData) which (ofc) is not available.

It sure is wrong to presume `AudioContext.decodeAudioData` is present but [the script](https://cdn.livechatinc.com/widget/static/js/iframe.846daba4.chunk.js) is 3rd-party and I have no control over it.

I wonder if we could / should provide a dummy function returning nothing or some dummy data.

Here's the stack trace:

```
RuntimeException: TypeError: Cannot find function decodeAudioData in object [object AudioContext]. (https://cdn.livechatinc.com/widget/static/js/iframe.846daba4.chunk.js#1)
net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot find function decodeAudioData in object [object AudioContext]. (https://cdn.livechatinc.com/widget/static/js/iframe.846daba4.chunk.js#1)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4325)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4303)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4336)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4355)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4431)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2604)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2586)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1520)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1010)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
        at com.gargoylesoftware.htmlunit.javascript.host.Promise.<init>(Promise.java:127)
        at sun.reflect.GeneratedConstructorAccessor538.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at net.sourceforge.htmlunit.corejs.javascript.MemberBox.newInstance(MemberBox.java:222)
        at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:456)
        at com.gargoylesoftware.htmlunit.javascript.RecursiveFunctionObject.call(RecursiveFunctionObject.java:190)
        at net.sourceforge.htmlunit.corejs.javascript.BaseFunction.construct(BaseFunction.java:366)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1719)
        at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1010)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111)
        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:424)
        at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3619)
        at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at com.gargoylesoftware.htmlunit.javascript.host.Promise$3.run(Promise.java:388)
        at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424)
        at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rbri** [comment]
I guess this is possible, will work on this the next days.

**Comment by rbri** [comment]
Made a first simple impl and will make a new snapshot build available. Please have a look and check if this is sufficcent for your case.

**Comment by black-snow** [comment]
Great! Tell me when it's ready.

**Comment by rbri** [comment]
SNAPSHOT is already available

**Comment by black-snow** [comment]
*2.36.0-SNAPSHOT* seems to work fine - awesome! Thanks @rbri
