### ISSUE TITLE
There is a problem with the use of js... I don't know how to solve it

### ISSUE THREAD

**Issue by Lou0083** [HtmlUnit/htmlunit#379]
Caused by: java.lang.RuntimeException: com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: yield expression must be parenthesized. (https://static.xx.fbcdn.net/rsrc.php/v3igeO4/y7/l/zh_CN/iyWVKZDQNIPVrQ15HKoyy59zNy60-L8c2tfDZMWFVfcOo_b_UBU0oC98S8EgyYK3ru9dc_Hnwms202U3pjSNA6nK6tbZQtAZAKKRcgCCePAsHPyZF5upFICYfwnEA3iceDmwNrev8VaiJLB-ZGvT57aeHAR78QIppYD_8nctNLKI022UWRR9xf6SLqS3gPjsVeIpNvHaOYaLZD-XL17qKRMUU4466HGfJ2lme3B0pcIigxpTOMM0nE-DG8o7pvORwt8sGWcSuyIuDuR5mjVvW5sqtyLC4liSpmERJXZLKBgsNrEVFvRYcuFZylffL4Q66gWs5vpRAS.js?_nc_x=VRFKi6hACR5#242)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:327)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:654)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:456)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:368)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:541)
	at sample.App.CheckDeals.CheckDealsController.submit(CheckDealsController.java:54)
	... 41 more

**Comment by ashleyfrieze** [comment]
That does look like an error in the javascript of your page, rather than an error in HtmlUnit. What's inside that big js file? and which version of JS is it compiled for?

**Comment by asbachb** [comment]
I'm getting the same error on accessing twitter profiles: https://twitter.com/Google

**Comment by rbri** [comment]
> yield expression must be parenthesized

Looks like a problem with Rhino - any chance to provide a simple js that produces this error?

**Comment by asbachb** [comment]
I don't think I can condense that JS. But here's a code to produce the error.

```java
try (final WebClient webClient = new WebClient()) {
    webClient.getPage("https://twitter.com/Google");
}
```

**Comment by altair441n** [comment]
Is there any solution?
