### ISSUE TITLE
Unable to download javascript error when using java 8 on windows. but works with java >= 9

### ISSUE THREAD

**Issue by danteCarvalho** [HtmlUnit/htmlunit#396]
I get this error when i try to run this line 
```java
HtmlPage page = webClient.getPage("https://cosmos.bluesoft.com.br/pesquisar?q=nescau");

```

out 27, 2021 2:59:19 PM com.gargoylesoftware.htmlunit.javascript.DefaultJavaScriptErrorListener loadScriptError
GRAVE: Error loading JavaScript from [https://api.radar.cloudflare.com/beacon.js].
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 503 Service Temporarily Unavailable for https://api.radar.cloudflare.com/beacon.js
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:759)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1065)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1002)
	at com.gargoylesoftware.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:196)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeDeferredScriptsIfNeeded(HtmlPage.java:1474)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:259)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:704)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:586)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:501)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:413)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:548)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:529)
	at Teste.main(Teste.java:20)

Exception in thread "main" com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 503 Service Temporarily Unavailable for https://api.radar.cloudflare.com/beacon.js
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:759)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1065)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1002)
	at com.gargoylesoftware.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:196)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeDeferredScriptsIfNeeded(HtmlPage.java:1474)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:259)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:704)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:586)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:501)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:413)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:548)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:529)
	at Teste.main(Teste.java:20)

it works on my ubuntu with java >=8 
fail on windows and java 8 but works with java >= 9
whats is weird is that it fails on my AWS ubuntu pc, with java 8 

i tryed with oracle jdk and liberica jdk, same error on both

**Comment by rbri** [comment]
strange - you are sure this is related to the jdk; maybe it is more machine dependent (proxy).

Can you try to trace the communication (wire log see https://hc.apache.org/httpcomponents-client-5.1.x/logging.html) to figure out if there are any differences?

Do you use a socks proxy?

**Comment by danteCarvalho** [comment]
Ok i solved the problem. No i don't use any proxy. Well, it is indeed a jdk issue, java 8 doesn't  have  TLS 1.3 enabled by default. And some sites require TLS 1.3 to work. TLS 1.3 was not even implemented until java 8u261. (i didn't know oracle had java 8 updates after java 8u202 until now). Now i am using java 8u311 released in October 19, 2021, all you need to do to make it work is set one of these jvm properties :

-Djdk.tls.client.protocols="TLSv1.3,TLSv1.2" or -Dhttps.protocols="TLSv1.3,TLSv1.2"

More information here https://www.java.com/en/configure_crypto.html
 
Oh, and i have no idea why it worked on my ubuntu pc :/

**Comment by rbri** [comment]
Thanks for the Info.
