### ISSUE TITLE
An error occurred while loading the Vue or React page

### ISSUE THREAD

**Issue by liming1010** [HtmlUnit/htmlunit#409]
Exception class=[net.sourceforge.htmlunit.corejs.javascript.EvaluatorException]
com.gargoylesoftware.htmlunit.ScriptException: syntax error ***

`Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: syntax error (http://***/static/js/chunk-libs.0adea9b6.js#141)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:436)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:251)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.reportError(Parser.java:330)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.reportError(Parser.java:321)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.reportError(Parser.java:314)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3114)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2665)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2568)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expExpr(Parser.java:2488)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2471)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2457)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2440)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2418)`

**Comment by trajano** [comment]
Dupe of https://github.com/HtmlUnit/htmlunit/issues/188

**Comment by rbri** [comment]
see #755
