### ISSUE TITLE
illegal character

### ISSUE THREAD

**Issue by linht12** [HtmlUnit/htmlunit#450]
Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: illegal character: � (http://j5.dfcfw.com/sc/js/trade/Hot_Em_CommonNew_min_20200410101224.js#1)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:433)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:257)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:235)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:241)
	at net.sourceforge.htmlunit.corejs.javascript.TokenStream.getToken(TokenStream.java:1271)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.peekToken(Parser.java:396)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.name(Parser.java:3191)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:3095)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2700)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2603)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expExpr(Parser.java:2523)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2506)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2492)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2475)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2453)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2429)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2420)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2411)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2402)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2393)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2384)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2351)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2309)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.expr(Parser.java:2292)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.nameOrLabel(Parser.java:2050)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1240)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.statement(Parser.java:1104)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:632)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.parse(Parser.java:562)
	at net.sourceforge.htmlunit.corejs.javascript.Context.parse(Context.java:2541)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2472)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1440)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:221)
	at net.sourceforge.htmlunit.corejs.javascript.Context.compileString(Context.java:1428)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:776)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:939)
	... 87 common frames omitted

**Comment by rbri** [comment]
Can you please add the Url you are using and the HtmlUnit version.

**Comment by linht12** [comment]
The URL of HTML is：http://fund.eastmoney.com/010990.html
The URL of js is：http://j5.dfcfw.com/sc/js/trade/Hot_Em_CommonNew_min_20200410101224.js
The htmlunit version is：2.58.0

**Comment by linht12** [comment]
@rbri 
The URL of HTML is：http://fund.eastmoney.com/010990.html
The URL of js is：http://j5.dfcfw.com/sc/js/trade/Hot_Em_CommonNew_min_20200410101224.js
The htmlunit version is：2.58.0

**Comment by rbri** [comment]
@linht12 thanks, will have a look

**Comment by rbri** [comment]
think i found the reason - as always writing the unit tests requires some time, hope to have the fix ready soon

**Comment by rbri** [comment]
Fixed, many thanks for the report - based on your info it was easy to reproduce. Please check twitter - will make a new snapshot build available soon.
And please verify the results, because i can't read Chinese :-)
