### ISSUE TITLE
com.gargoylesoftware.htmlunit.ScriptException: TypeError:

### ISSUE THREAD

**Issue by alinelsilva** [HtmlUnit/htmlunit#456]
I'm trying to access a link but I'm getting this error.

 ERROR 47351 --- [Client@7866a7a6] c.g.h.j.DefaultJavaScriptErrorListener   : Error during JavaScript execution

com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot find function includes in object function onblur(event) {RestauraNFSeURL();
}. (https://notacarioca.rio.gov.br/Scripts/jquery-3.5.1.min.js#2)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:883) ~[htmlunit-2.36.0.jar:2.36.0]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:617) ~[htmlunit-core-js-2.36.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:534) ~[htmlunit-core-js-2.36.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:336) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:812) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:784) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2542) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2535) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptFunctionJob.runJavaScript(JavaScriptFunctionJob.java:57) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptExecutionJob.run(JavaScriptExecutionJob.java:102) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:424) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:148) ~[htmlunit-2.36.0.jar:2.36.0]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: TypeError: Cannot find function includes in object function onblur(event) {RestauraNFSeURL();
}. (https://notacarioca.rio.gov.br/Scripts/jquery-3.5.1.min.js#2)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1216) ~[htmlunit-core-js-2.36.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1010) ~[htmlunit-core-js-2.36.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:111) ~[htmlunit-core-js-2.36.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:424) ~[htmlunit-core-js-2.36.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:322) ~[htmlunit-2.36.0.jar:2.36.0]
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3628) ~[htmlunit-core-js-2.36.0.jar:na]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:805) ~[htmlunit-2.36.0.jar:2.36.0]
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:868) ~[htmlunit-2.36.0.jar:2.36.0]
	... 12 common frames omitted

2022-03-07 14:32:26.953 ERROR 47351 --- [Client@7866a7a6] c.g.h.j.b.JavaScriptJobManagerImpl       : Job run failed with unexpected RuntimeException: TypeError: Cannot find function includes in object function onblur(event) {RestauraNFSeURL();
}. (https://notacarioca.rio.gov.br/Scripts/jquery-3.5.1.min.js#2)

![image](https://user-images.githubusercontent.com/22075156/157090050-5c17e699-8507-4587-a0c2-72dce15d360e.png)

**Comment by rbri** [comment]
i think htmlunit is correct here, the site shows the same error when calling from the browser
![image](https://user-images.githubusercontent.com/2544132/157096040-163030fa-9dd6-4461-aaf1-0db6dbe59822.png)

think about setting this option

        // procced with the js execution on unhandled js errors
         webClient.getOptions().setThrowExceptionOnScriptError(false);

see e.g. https://htmlunit.sourceforge.io/webclient.html for more

**Comment by alinelsilva** [comment]
I added this line already, but the error continues, I added a few others as I searched, but the error persists.

![image](https://user-images.githubusercontent.com/22075156/157102422-d22b1b00-5d44-4c86-be09-fb2a90014278.png)

**Comment by rbri** [comment]
Ah, ok i guess there is a misunderstanding - the error itself is in the webpage and so the error persists. The only one that can solve this is the owner of the webpage by fixing the error.

The only thing the setThrowExceptionOnScriptError(false) setting does, is to make HtmlUnit behaving like real browser and ignoring (but still logging) the error but proceed with the js execution
You will still see the report in your logs but this is the same as for the browsers - the error is visible in the console (see my screenshot).

**Comment by alinelsilva** [comment]
So in that case there's not much to do about it? Your print didn't come.

**Comment by rbri** [comment]
The print was on my first comment, it is a screenshot from the console of the real browser

I think you simply have to ignore this error....

**Comment by alinelsilva** [comment]
I understand. Thanks!
