### ISSUE TITLE
Add support for Jasmine 4.0.1

### ISSUE THREAD

**Issue by tntim96** [HtmlUnit/htmlunit#472]
I've just tried upgrading `JSCover` to use Jasmine 4.0.1 and when running `HtmlUnitJSTest` I get:
```
Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: syntax error (http://localhost:8081/src/test/javascript/lib/jasmine-4.0.1/jasmine.js#871)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:433)
	at net.sourceforge.htmlunit.corejs.javascript.Parser.addError(Parser.java:257)
```

That line of JavaScript in Jasmine 4.0.1 is the 3rd one below:
```
    var runnerConfig = {  //Line 869
      isLeaf: true,
      queueableFns: [...fns.befores, this.queueableFn, ...fns.afters],
```

**Comment by rbri** [comment]
hava added a test case; fails at the moment because jasmine 4.6.1 uses async
