### ISSUE TITLE
Incompatibility with bootstrap-table (Cannot modify readonly property: constructor)

### ISSUE THREAD

**Issue by deligkarisk** [HtmlUnit/htmlunit#475]
I have a page that is using [bootstrap-table  ](https://bootstrap-table.com/) and I am trying to test it with HtmlUnit (SpringBoot with Thymeleaf)

This is what I get when I try to run
`HtmlPage htmlPage = webClient.getPage("requestTopage");`

``` 
2022-04-08 14:37:00.581  WARN 97895 --- [           main] c.g.htmlunit.DefaultCssErrorHandler      : CSS error: 'https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css' [1:2912] Error in declaration. '*' is not allowed as first char of a property.
2022-04-08 14:37:00.588  WARN 97895 --- [           main] c.g.htmlunit.DefaultCssErrorHandler      : CSS error: 'https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css' [1:9325] Error in declaration. '*' is not allowed as first char of a property.
2022-04-08 14:37:00.594  WARN 97895 --- [           main] c.g.htmlunit.DefaultCssErrorHandler      : CSS error: 'https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css' [1:13045] Error in declaration. '*' is not allowed as first char of a property.
2022-04-08 14:37:01.576 ERROR 97895 --- [           main] c.g.h.j.DefaultJavaScriptErrorListener   : Error during JavaScript execution

com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot modify readonly property: constructor. (https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.10.21/libs/jsPDF/jspdf.min.js#37)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:949) ~[htmlunit-2.45.0.jar:2.45.0]
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:619) ~[htmlunit-core-js-2.45.0.jar:na]
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:537) ~[htmlunit-core-js-2.45.0.jar:na]
```

It seems to be similar to earlier problems, but I am not overly sure either (e.g. https://sourceforge.net/p/htmlunit/bugs/1974/)

**Comment by rbri** [comment]
Issue was fixed with 2.68.0. Thanks for reporting.
Please open a new one if your face problems with the latest version.
