### ISSUE TITLE
CSSException: Invalid selector: *:-moz-placeholder-shown

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#483]
I'm getting the exception when calling HTMLElement.getOffsetHeight()
```
com.gargoylesoftware.css.parser.CSSException: Invalid selector: *:-moz-placeholder-shown
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.validateSelectors(CSSStyleSheet.java:1616)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.selectsPseudoClass(CSSStyleSheet.java:911)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.selects(CSSStyleSheet.java:616)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.selects(CSSStyleSheet.java:459)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.selects(CSSStyleSheet.java:478)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.selects(CSSStyleSheet.java:1818)
	at com.gargoylesoftware.htmlunit.javascript.host.css.CSSStyleSheet.modifyIfNecessary(CSSStyleSheet.java:276)
	at com.gargoylesoftware.htmlunit.WebWindowImpl.getComputedStyle(WebWindowImpl.java:421)
	at com.gargoylesoftware.htmlunit.javascript.host.Window.getComputedStyle(Window.java:1645)
```

**Comment by rbri** [comment]
Hi @RuralHunter - this is fixed and a new snapshot available.
Will try to find some time to work on your other issues also.

**Comment by RuralHunter** [comment]
Thanks!
