### ISSUE TITLE
ReferenceError: "variableName" is not defined.

### ISSUE THREAD

**Issue by gaellalire** [HtmlUnit/htmlunit#491]
I got 
```java
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:597)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$7(HtmlUnitDriver.java:561)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.gargoylesoftware.htmlunit.ScriptException: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:996)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2606)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.lambda$executeEventHandlersIfNeeded$1(HtmlPage.java:1292)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1292)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:322)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:708)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:590)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:508)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:579)
	... 5 more
Caused by: java.lang.RuntimeException: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:344)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:708)
	at com.gargoylesoftware.htmlunit.WebClient.loadDownloadedResponses(WebClient.java:2547)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:1024)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:991)
	... 26 more
Caused by: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:996)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2606)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
	at com.gargoylesoftware.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1491)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.html.DomElement.fireEvent(DomElement.java:1491)
	at com.gargoylesoftware.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:949)
	at com.gargoylesoftware.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319)
	at com.gargoylesoftware.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:337)
	... 30 more
Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4613)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4594)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4682)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:2023)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.name(ScriptRuntime.java:1961)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1977)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1053)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:335)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3916)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:916)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:979)
	... 49 more
Caused by: com.gargoylesoftware.htmlunit.ScriptException: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:996)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2606)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.lambda$executeEventHandlersIfNeeded$1(HtmlPage.java:1292)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1292)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:322)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:708)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:590)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:508)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:415)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:579)
	... 5 more
Caused by: java.lang.RuntimeException: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:344)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:708)
	at com.gargoylesoftware.htmlunit.WebClient.loadDownloadedResponses(WebClient.java:2547)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:1024)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:991)
	... 26 more
Caused by: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:996)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2606)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
	at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
	at com.gargoylesoftware.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1491)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
	at com.gargoylesoftware.htmlunit.html.DomElement.fireEvent(DomElement.java:1491)
	at com.gargoylesoftware.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:949)
	at com.gargoylesoftware.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319)
	at com.gargoylesoftware.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:337)
	... 30 more
Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: ReferenceError: "OnetrustActiveGroups" is not defined. (script in https://secureidentity.schneider-electric.com/idp/login?app=0sp1H000000PBCG&binding=HttpPost&inresponseto=a38i1g71gi1deag14508fcjgd1ghie5 from (-1, -1) to (-1, -1)#1)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4613)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4594)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4682)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:2023)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.name(ScriptRuntime.java:1961)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1977)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1053)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:335)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3916)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:916)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:979)
	... 49 more

```

But the chrome browser doesn't seem to care.

**Comment by gaellalire** [comment]
You can reproduce with same example as before https://gaellalire.fr/npe/npe_test.zip

**Comment by rbri** [comment]
Will have a look....

**Comment by rbri** [comment]
@gaellalire 
Did some analysis and there are good and bad news

good news
The problem you reported is solvable (see e.g. https://htmlunit.sourceforge.io/faq.html#javaScriptExceptions)

the bad news
Did some tests and it looks like clicking the next button does not forward to the password input. I fear this is because the page is implemented with angular and HtmlUnit has some open problem with the complex js stuff they are doing.
Sorry for that but i will not have the time to dig deeper into this at the moment.

Feel free to analyze this in more detail, if you can point to some more specific problem in HtmlUnit i will try to fix that.

Sorry that is the state for the moment.

**Comment by gaellalire** [comment]
@rbri 
It was only a good news, I got it working only with ignoring javascript exception
Thank you
