### ISSUE TITLE
java.io.NotSerializableException

### ISSUE THREAD

**Issue by gangadharkasturi** [HtmlUnit/htmlunit#511]
Trying to scrape a page using htmlunit.. Encountering below issue with the framework. Please help and fix.

	fos = new FileOutputStream(file);
					byte[] by = SerializationUtils.serialize(page);
					out = new ObjectOutputStream(fos);
					out.writeObject(by);

org.apache.commons.lang3.SerializationException: java.io.NotSerializableException: com.gargoylesoftware.htmlunit.javascript.NativeFunctionToStringFunction$NativeFunctionToStringFunctionChrome
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:273)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:248)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)

Caused by: java.io.NotSerializableException: com.gargoylesoftware.htmlunit.javascript.NativeFunctionToStringFunction$NativeFunctionToStringFunctionChrome
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.writeObject(ScriptableObject.java:2652)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptableObject.writeObject(ScriptableObject.java:2643)

**Comment by gangadharkasturi** [comment]
URL trying to scrape: https://udyamregistration.gov.in/Udyam_Verify.aspx

Here I am trying to serialize the page and saving to disk which is resulting above error.

**Comment by rbri** [comment]
Why you like to serialize the page - maybe you like to do something like page.asXML()?

**Comment by gangadharkasturi** [comment]
I want to serialize and save the page so that my next request will pick the same page and deserialize and enters the captcha value to get the information.

**Comment by rbri** [comment]
and you will stop/start the jvm before the next request?

**Comment by gangadharkasturi** [comment]
The process is : 
In the first request, I will capture this page and save it on disk by serializing the page.
In the second request, I will deserialize the object to page and again perfom some operation and send back the response.

I am encountering the issue when I try to save the page on to disk, it is throwing the mentioned exception.

Let me know if you have any other questions please.

**Comment by gangadharkasturi** [comment]
> and you will stop/start the jvm before the next request?



> and you will stop/start the jvm before the next request?

Could you pls check my above comment?

**Comment by rbri** [comment]
fixed, please use the latest snapshot

**Comment by gangadharkasturi** [comment]
Thanks for fixing it out. But here is the another issue raised after fixing the above one.

2022-10-21 17:33:47 [JS executor for com.gargoylesoftware.htmlunit.WebClient@65732010] WARN  c.g.h.IncorrectnessListenerImpl - Obsolete content type encountered: 'text/javascript'.
java.io.NotSerializableException: com.gargoylesoftware.htmlunit.javascript.host.Element$$Lambda$81/543270429
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
