### ISSUE TITLE
com.gargoylesoftware.htmlunit.javascript.host.Element$$Lambda$81/543270429

### ISSUE THREAD

**Issue by gangadharkasturi** [HtmlUnit/htmlunit#513]
Thanks for fixing it out. But here is the another issue raised after fixing the above one.

2022-10-21 17:33:47 [JS executor for com.gargoylesoftware.htmlunit.WebClient@65732010] WARN  c.g.h.IncorrectnessListenerImpl - Obsolete content type encountered: 'text/javascript'.
java.io.NotSerializableException: com.gargoylesoftware.htmlunit.javascript.host.Element$$Lambda$81/543270429
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

_Originally posted by @gangadharkasturi in https://github.com/HtmlUnit/htmlunit/issues/511#issuecomment-1286873060_

**Comment by rbri** [comment]
made a new snapshot build - please try

**Comment by gangadharkasturi** [comment]
Thank you @rbri, I'll try and let you know

**Comment by gangadharkasturi** [comment]
2022-10-22 08:09:31 [JS executor for com.gargoylesoftware.htmlunit.WebClient@76bb4792] WARN  c.g.h.IncorrectnessListenerImpl - Obsolete content type encountered: 'text/javascript'.
java.io.NotSerializableException: com.gargoylesoftware.htmlunit.html.StaticDomNodeList
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)

**Comment by gangadharkasturi** [comment]
StaticDomNodeList : Fixed the issue, it is working fine. Please accept my pull request to make the changes.

**Comment by rbri** [comment]
sorry i have created my own patch - please rebase your repo before working on more pull requests.
A new snapshot build is available - please test.

Thanks for the report - and more pull requests are welcome.

**Comment by gangadharkasturi** [comment]
Thanks for all the support, will surely contribute from my side.
