### ISSUE TITLE
HtmlUnit delays JVM shutdown

### ISSUE THREAD

**Issue by DaniRey** [HtmlUnit/htmlunit#56]
HtmlUnitDriver somehow delays the shutdown process of the JVM. 

```
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

public class HtmlUnitJavaRunner {
    public static void main(String[] args) {
        System.out.println("start");
        HtmlUnitDriver htmlUnitDriver = new HtmlUnitDriver(false);
        //comment the following line and there will be no delay during JVM shutdown
        htmlUnitDriver.get("http://htmlunit.sourceforge.net/images/internet-web-browser.png");
        htmlUnitDriver.quit();
        System.out.println("finish");
        //the JVM takes roughly 1 minute to shutdown after writing "finish" to the console
    }
}
```

The following ThreadDump was taken after "finish" was printed to the console. Therefore also after `htmlUnitDriver.quit()` was called.

```
Full thread dump

"Monitor Ctrl-Break" #6 daemon prio=5 os_prio=0 tid=0x000000001e2fb000 nid=0x350 runnable [0x000000001e4fe000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000077072a9f8> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x000000077072a9f8> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:64)


"pool-1-thread-1" #13 prio=5 os_prio=0 tid=0x0000000020e25000 nid=0x5a0c waiting on condition [0x0000000021cdf000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000770202928> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000000345b800 nid=0x5ad4 in Object.wait() [0x000000001dd0e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000077072aed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000077072aed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)


"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x000000001c99a000 nid=0x6478 in Object.wait() [0x000000001dc0f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000077072b088> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000077072b088> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)


"DestroyJavaVM" #14 prio=5 os_prio=0 tid=0x0000000003367000 nid=0x4b34 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"Service Thread" #10 daemon prio=9 os_prio=0 tid=0x000000001e3ec000 nid=0x108c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"C1 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x000000001e35b800 nid=0x5084 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x000000001e32b800 nid=0x4c8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x000000001e328800 nid=0x6194 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000001c9b3000 nid=0x4abc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000001c9b1800 nid=0x5ce0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE


"VM Thread" os_prio=2 tid=0x000000001c979000 nid=0x24a8 runnable 


"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x000000000337c000 nid=0x64f4 runnable 


"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x000000000337e000 nid=0x6914 runnable 


"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x000000000337f800 nid=0x56fc runnable 


"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000003381000 nid=0x744 runnable 


"VM Periodic Task Thread" os_prio=2 tid=0x000000001e9e0800 nid=0x561c waiting on condition 
JNI global references: 244


````

**Comment by DaniRey** [comment]
The problem can be reproduced with htmlunit-driver version 2.35.1 (but also 2.32.1).
The problem is not Intellij specific, the same happens using plain `javac` and `java`.

As far as I can tell, some test runners stop the process anyway (or report back with having it running in the background). At least the problem cannot be reproduced running HtmlUnit via ScalaTestRunner from Intellij.

**Comment by rbri** [comment]
This is a bug in the HtmlUnit driver. Have fixed this. User the latest HtmlUnitDriver SNAPSHOT (at least 2.36.0-SNAPSHOT).
Many thanks for this report.

**Comment by DaniRey** [comment]
@rbri Thanks a lot!

Of course I was interested to learn what the issue/solution was. The fix is in https://github.com/SeleniumHQ/htmlunit-driver/commit/f1faf7b0e241e7d2779f51f82b7adbe7bf4250f2

Apparanetly if the executor is a java.util.concurrent.ExecutorService, `.shutdown()` has to be executed as part of the tear down process. I learned something and leave this comment for other to learn too.
