### ISSUE TITLE
identifier is a reserved word: class (xxx/static/js/cache-h5-dcloudio.js#1)

### ISSUE THREAD

**Issue by Den-Jun** [HtmlUnit/htmlunit#579]
Hi, @rbri  hello. I am having trouble using it.
` 
ERROR o.a.c.l.i.Jdk14Logger:log   Error during JavaScript execution
org.htmlunit.ScriptException: identifier is a reserved word: class (https://XXX/static/js/cache-h5-dcloudio.js#1)
        at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:989)
        at org.htmlunit.corejs.javascript.Context.call(Context.java:590)
        at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
        at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
  `
  version：
  `
<dependency>
         <groupId>org.htmlunit</groupId>
         <artifactId>htmlunit</artifactId>
         <version>3.0.0</version>
       </dependency>
`
The 'cache-h5-dcloudio.js' is a compressed file used for deployment in the front-end. We have tested that if the code is not compressed during deployment, it will work normally.
We felt very strange about it.

The front-end compression component is "vue-cli-plugin-uni", with a version of 2.0.2-3070920230324001. Then we rolled back the version of the component to "2.0.0-27920200618002", and everything was normal.

Thank you.

**Comment by sengsational** [comment]
This might be similar to https://github.com/HtmlUnit/htmlunit/issues/480

**Comment by rbri** [comment]
see #755
