### ISSUE TITLE
Cleaning up memory leak without completely destroying the driver?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#639]
I've been running HtmlUnit via Selenium in 16 threads for hours and noticed the memory is accumulating over time.

Destroying the driver is one solution I am looking into, but so far it seems like most of the leakage is from javascript.

Is there a clean way to purge a driver or HtmlUnit itself to close all active pages, terminating and cleaning up any related javascript objects as well?

The workaround is to remember when a driver was instantiated and if it has been alive for long enough, save the cookies, destroy the driver, spin up a new one and inject the cookies back. But that is a lot of work just to do cleanup.

**Comment by rbri** [comment]
Have done some work on the WebClient close implementation, you ca try this by using the latest HtmlUnit snapshot. But not sure if this helps for your problem, because you can't use the client afterwards.

Maybe i have to look at this again...

**Comment by skyhirider** [comment]
Thanks rbri, if it makes the client unusable then its easier to kill the driver completely and reset. 

My first guess would be that the javascript code is leaking, if there was a way to reliably reset that without affecting anything else it would make for a nice test to see which component is leaking.

I implemented opening "data:,empty" before returning the driver to a pool, but that did not seem to do anything. Was hoping it would kill the javascript running in the background and allow the garbage collector to do its work.

**Comment by rbri** [comment]
While thinking about it i guess i can do something better here. But you have to wait until I'm back from vacation

**Comment by rbri** [comment]
Have added a new method WebClient.reset() - hope this does the trick for you. Will inform you later if a new snapshot is available for testing

**Comment by rbri** [comment]
@skyhirider  just made a new HtmlUnit release - please have a look

**Comment by rbri** [comment]
Will close this - 3.7.0-SNAPSHOT has another major fix for the memory handling https://github.com/HtmlUnit/htmlunit/commit/7c19e26db8563917f6bf020ae3af5f04d193394d

**Comment by skyhirider** [comment]
Thanks @rbri ! Will play around with the setting once I have a bit more time to test to see if that fixed the issues I was seeing.

**Comment by rbri** [comment]
@skyhirider please try to use also the latest 3.7.0-SNAPSHOT because of the major fix

**Comment by skyhirider** [comment]
@rbri seems reset is not working, at least when I test it. 

```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

public class ResetTest {

    public static final String TEST_SITE = "https://www.google.com";
    private final HtmlUnitDriver driver = new HtmlUnitDriver();

    @Test
    void givenPageWithJavascript_keepReloading_dontIncreaseMemoryUsage(){
        driver.get(TEST_SITE);
        driver.getWebClient().reset();
        Assertions.assertDoesNotThrow(() -> driver.get(TEST_SITE));
    }
}
```

```
org.opentest4j.AssertionFailedError: Unexpected exception thrown: org.openqa.selenium.WebDriverException: org.openqa.selenium.NoSuchWindowException: Window is closed
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'
Driver info: driver.version: HtmlUnitDriver

	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3136)
	at ResetTest.givenPageWithJavascript_keepReloading_dontIncreaseMemoryUsage(ResetTest.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.openqa.selenium.WebDriverException: org.openqa.selenium.NoSuchWindowException: Window is closed
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:671)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$7(HtmlUnitDriver.java:627)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:353)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.openqa.selenium.NoSuchWindowException: Window is closed
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'
Driver info: driver.version: HtmlUnitDriver
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.getCurrentWindow(HtmlUnitDriver.java:1209)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:647)
	... 5 more
```

**Comment by skyhirider** [comment]
An example of a very inefficient reset that destroys everything except cookies:
```java
    @Test
    void givenPageWithCookies_whenReloadingDriver_rememberCookies(){
        WebDriver cookieDriver = new HtmlUnitDriver();
        cookieDriver.get(TEST_SITE);
        final Set<Cookie> cookies = cookieDriver.manage().getCookies();
        Assertions.assertEquals(".google.com",cookies.stream().findFirst().get().getDomain());
        cookieDriver.close();
        cookieDriver = new HtmlUnitDriver();
        Assertions.assertEquals(Optional.empty(),cookieDriver.manage().getCookies().stream().findFirst());
        WebDriver finalCookieDriver = cookieDriver;
        finalCookieDriver.get(TEST_SITE);
        finalCookieDriver.manage().deleteAllCookies();
        cookies.forEach(c -> finalCookieDriver.manage().addCookie(c));
        Assertions.assertEquals(".google.com",cookies.stream().findFirst().get().getDomain());
    }
```
Not impressed by Selenium's inability to inject cookies unless the driver is on that page first. Would make it extremely tedious to re-add a large cookie set spread across domains. Luckily not my case, but still surprised running the test above without `finalCookieDriver.get(TEST_SITE);` results in 
```
org.openqa.selenium.InvalidCookieDomainException: You may only add cookies that would be visible to the current domain: .google.com => .
```

**Comment by rbri** [comment]
@skyhirider  will have a look and come back to you

**Comment by rbri** [comment]
@skyhirider sorry but it was a long ride to made some progress here. Hope i got it now - please try htmlunit3-driver 4.14.1-SNAPSHOT and report your findings here.

Have a nice weekend....

**Comment by skyhirider** [comment]
Thanks! The test is passing, will try out the reset on a larger scale to see how it will behave.

Is it safe to re-inject cookies to htmlunit directly without visiting a page and is there a way to make it so when controlling via the driver, or is it a Selenium specification that we can't inject cookies back without actually being on that domain with our active window?

**Comment by skyhirider** [comment]
Seems to be working, thou am seeing these messages.

What I am doing is taking a driver from a pool, doing a few taks then cleaning it up and returning to be pulled out later for another task.

I'm assuming even after getting an empty page ajax is running in the background. Would close all tabs to hopefully kill it but that would kill the driver as well, so resorted to loading an empty page instead.

driver.get("data:,empty");

15:10:07.177 [JS executor for org.htmlunit.WebClient@3607f65d] INFO  org.htmlunit.javascript.JavaScriptEngine - handleJavaScriptException('No node attached to this object (https://domain/someJavascript.js#1234)') called after the shutdown of the Javascript engine - exception ignored.


15:10:39.640 [JS executor for org.htmlunit.WebClient@429933ab] INFO  org.htmlunit.javascript.JavaScriptEngine - handleJavaScriptException('Exception invoking getOffsetWidth') called after the shutdown of the Javascript engine - exception ignored.
