### ISSUE TITLE
Caused by: org.htmlunit.corejs.javascript.EvaluatorException: missing formal parameter

### ISSUE THREAD

**Issue by gangadharkasturi** [HtmlUnit/htmlunit#646]
Caused by: org.htmlunit.corejs.javascript.EvaluatorException: missing formal parameter (https://xxxxxxx/1.js)
	at org.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:434)
	at org.htmlunit.corejs.javascript.Parser.addError(Parser.java:257)
	at org.htmlunit.corejs.javascript.Parser.reportError(Parser.java:336)
	at org.htmlunit.corejs.javascript.Parser.reportError(Parser.java:332)
	at org.htmlunit.corejs.javascript.Parser.arrowFunctionParams(Parser.java:1040)
	at org.htmlunit.corejs.javascript.Parser.arrowFunction(Parser.java:977)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2355)
	at org.htmlunit.corejs.javascript.Parser.argumentList(Parser.java:2681)
	at org.htmlunit.corejs.javascript.Parser.memberExprTail(Parser.java:2825)
	at org.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:2745)
	at org.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:2613)
	at org.htmlunit.corejs.javascript.Parser.expExpr(Parser.java:2533)
	at org.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:2516)
	at org.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:2502)
	at org.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2485)
	at org.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2463)
	at org.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:2439)
	at org.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:2430)
	at org.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:2421)
	at org.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:2412)
	at org.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:2403)
	at org.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2394)
	at org.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:2361)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:2319)
	at org.htmlunit.corejs.javascript.Parser.expr(Parser.java:2302)
	at org.htmlunit.corejs.javascript.Parser.nameOrLabel(Parser.java:2060)
	at org.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:1239)
	at org.htmlunit.corejs.javascript.Parser.statement(Parser.java:1103)
	at org.htmlunit.corejs.javascript.Parser.parse(Parser.java:631)
	at org.htmlunit.corejs.javascript.Parser.parse(Parser.java:561)
	at org.htmlunit.corejs.javascript.Context.parse(Context.java:2549)
	at org.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2480)
	at org.htmlunit.corejs.javascript.Context.compileString(Context.java:1448)
	at org.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:220)
	at org.htmlunit.corejs.javascript.Context.compileString(Context.java:1436)
	at org.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:835)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:997)
	... 36 more
Enclosed exception:

**Comment by gangadharkasturi** [comment]
any update on this?

**Comment by gangadharkasturi** [comment]
any update on this? It's been a long time.. :)

**Comment by rbri** [comment]
@gangadharkasturi sorry not really. Have done a lot of work on Rhino during the last months but there is much more to do. And please keep in mind that i'm doing all the stuff in my spare time.

There is a plan to be more independent from core-js and then try to use another more recent js engine. But this is only a plan - maybe i will start on this at the beginning of next year.

**Comment by rbri** [comment]
@gangadharkasturi the plan is now a bit more concrete https://github.com/HtmlUnit/htmlunit/issues/755
