### ISSUE TITLE
Scroll event not triggering correctly?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#657]
I've ran into a case where triggering javascript scrollintoView has no effect, not triggering an event that is supposed to dynamically load the next page of data. 

Here is a basic test case:

```java
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;

public class ScrollTest {

    public static final String PAGE;

    static {
        try {
            PAGE = Files.readString(Path.of(ScrollTest.class.getClassLoader().getResource("testPage1.html").toURI()));
        } catch (IOException | URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }

    private static final HtmlUnitDriver huDriver = new HtmlUnitDriver(true);
    private static final WebDriver chromeDriver = new ChromeDriver();

    @AfterAll
    static void closeAll(){
        huDriver.close();
        chromeDriver.close();
    }

    @Test
    void givenPageWithTable_whenScrollTo_TriggerEvent(){
        runTest(chromeDriver);
        runTest(huDriver);
    }

    private static void runTest(WebDriver driver) {
        driver.get(PAGE);
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView()", driver.findElement(By.id("last")));
        Assertions.assertEquals(1L,
                ((JavascriptExecutor) driver).executeScript("return count"));
    }

}
```

and here is the html file I used for testing, feel free to add more table rows if needed

```html
data:text/html,
<table>
    <tr>row</tr>
    <br>
    <tr id="last"></tr>
</table>
<script>
    var count = 0;
    const observer = new IntersectionObserver((entries) => { 
    entries.forEach((entry) => {
        console.log("triggered");
        count++;
    })
}); 

observer.observe(document.getElementById("last"));
</script>
```

The results are incosistent:

```
org.opentest4j.AssertionFailedError: 
Expected :1
Actual   :0
<Click to see difference>

at ScrollTest.runTest(ScrollTest.java:45)
at ScrollTest.givenPageWithTable_whenScrollTo_TriggerEvent(ScrollTest.java:39)

...removed rest of generic stack trace...	
```

**Comment by skyhirider** [comment]
The first test triggers on load only, a second slightly modified test thats failing in a different way
```java
        private static void runTest(WebDriver driver) {
            driver.get(PAGE);
            JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
            jsExecutor.executeScript("arguments[0].scrollIntoView()", driver.findElement(By.id("last")));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            Assertions.assertEquals(2L,jsExecutor.executeScript("return count"));
        }
```
```
org.opentest4j.AssertionFailedError: 
Expected :2
Actual   :0
at ScrollTest.runTest(ScrollTest.java:51)
at ScrollTest.givenPageWithTable_whenScrollTo_TriggerEvent(ScrollTest.java:39)

```

Requires a very long set of <tr> and <br> tags in input so that the last tr is not visible on the window and requires a scroll

**Comment by skyhirider** [comment]
@rbri took me too long to get back to this, but created a live test case that is failing.

If the chrome driver fails when you run this, put a thread sleep after loading the page.

It always fails in HtmlUnit, tested on version 4.1.0

```java
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;

public class LiveScrollTest {

    private static final HtmlUnitDriver huDriver = new HtmlUnitDriver(true);
    private static final WebDriver chromeDriver = new ChromeDriver();
    private static final By scrollableElement = By.xpath("//a[@slot='full-post-link']");

    @AfterAll
    static void closeAll() {
        huDriver.close();
        chromeDriver.close();
    }

    @Test
    void givenPageWithLiveScroll_whenReachedLastElement_TriggerScrollReload() {
        runTest(chromeDriver);
        runTest(huDriver);
    }

    private static void runTest(WebDriver driver) {
        driver.get("https://www.reddit.com/r/news/");
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.numberOfElementsToBe(scrollableElement, 3));
        JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
        int countOfElementsBeforeScroll = getNumberOfElements(driver);
        jsExecutor.executeScript("arguments[0].scrollIntoView()", driver.findElement(By.xpath("(//a[@slot='full-post-link'])[last()]")));
        wait.until(ExpectedConditions.numberOfElementsToBeMoreThan(scrollableElement, countOfElementsBeforeScroll));
        System.out.println("Finished testing with ".concat(driver.getClass().getSimpleName()));
    }

    private static int getNumberOfElements(WebDriver driver) {
        return driver.findElements(scrollableElement).size();
    }

}
```

**Comment by skyhirider** [comment]
Ran this with 4.10.0 and test is still failing.
