### ISSUE TITLE
Error when compile JS

### ISSUE THREAD

**Issue by fsoudant** [HtmlUnit/htmlunit#659]
execute at line 2, column 2385 : identifier is a reserved word: class (https://e-cdn-files.dzcdn.net/cache/js/app-backstage-plain-html.49a17339cc5ea69b985f.js#2)
	at org.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.error(HtmlUnitContextFactory.java:432)
	at org.htmlunit.corejs.javascript.Parser.addError(Parser.java:3558)
	at org.htmlunit.corejs.javascript.Parser.reportError(Parser.java:3863)
	at org.htmlunit.corejs.javascript.Parser.reportError(Parser.java:3859)
	at org.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:2432)
	at org.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:1612)
	at org.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:3173)
	at org.htmlunit.corejs.javascript.Parser.expExpr(Parser.java:1111)
	at org.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:1782)
	at org.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:326)
	at org.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2718)
	at org.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2617)
	at org.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:1073)
	at org.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:720)
	at org.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:738)
	at org.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:729)
	at org.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:357)
	at org.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2031)
	at org.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:813)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:630)
	at org.htmlunit.corejs.javascript.Parser.expr(Parser.java:1130)
	at org.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:2856)
	at org.htmlunit.corejs.javascript.Parser.statement(Parser.java:2737)
	at org.htmlunit.corejs.javascript.Parser.parseFunctionBody(Parser.java:2194)
	at org.htmlunit.corejs.javascript.Parser.arrowFunction(Parser.java:582)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:658)
	at org.htmlunit.corejs.javascript.Parser.plainProperty(Parser.java:2371)
	at org.htmlunit.corejs.javascript.Parser.objectLiteral(Parser.java:1965)
	at org.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:2387)
	at org.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:1612)
	at org.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:3173)
	at org.htmlunit.corejs.javascript.Parser.expExpr(Parser.java:1111)
	at org.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:1782)
	at org.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:326)
	at org.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2718)
	at org.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2617)
	at org.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:1073)
	at org.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:720)
	at org.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:738)
	at org.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:729)
	at org.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:357)
	at org.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2031)
	at org.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:813)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:630)
	at org.htmlunit.corejs.javascript.Parser.variables(Parser.java:3237)
	at org.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:2811)
	at org.htmlunit.corejs.javascript.Parser.statement(Parser.java:2737)
	at org.htmlunit.corejs.javascript.Parser.parseFunctionBody(Parser.java:2194)
	at org.htmlunit.corejs.javascript.Parser.arrowFunction(Parser.java:582)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:658)
	at org.htmlunit.corejs.javascript.Parser.expr(Parser.java:1130)
	at org.htmlunit.corejs.javascript.Parser.parenExpr(Parser.java:2046)
	at org.htmlunit.corejs.javascript.Parser.primaryExpr(Parser.java:2393)
	at org.htmlunit.corejs.javascript.Parser.memberExpr(Parser.java:1612)
	at org.htmlunit.corejs.javascript.Parser.unaryExpr(Parser.java:3173)
	at org.htmlunit.corejs.javascript.Parser.expExpr(Parser.java:1111)
	at org.htmlunit.corejs.javascript.Parser.mulExpr(Parser.java:1782)
	at org.htmlunit.corejs.javascript.Parser.addExpr(Parser.java:326)
	at org.htmlunit.corejs.javascript.Parser.shiftExpr(Parser.java:2718)
	at org.htmlunit.corejs.javascript.Parser.relExpr(Parser.java:2617)
	at org.htmlunit.corejs.javascript.Parser.eqExpr(Parser.java:1073)
	at org.htmlunit.corejs.javascript.Parser.bitAndExpr(Parser.java:720)
	at org.htmlunit.corejs.javascript.Parser.bitXorExpr(Parser.java:738)
	at org.htmlunit.corejs.javascript.Parser.bitOrExpr(Parser.java:729)
	at org.htmlunit.corejs.javascript.Parser.andExpr(Parser.java:357)
	at org.htmlunit.corejs.javascript.Parser.orExpr(Parser.java:2031)
	at org.htmlunit.corejs.javascript.Parser.condExpr(Parser.java:813)
	at org.htmlunit.corejs.javascript.Parser.assignExpr(Parser.java:630)
	at org.htmlunit.corejs.javascript.Parser.expr(Parser.java:1130)
	at org.htmlunit.corejs.javascript.Parser.statementHelper(Parser.java:2856)
	at org.htmlunit.corejs.javascript.Parser.statement(Parser.java:2737)
	at org.htmlunit.corejs.javascript.Parser.parse(Parser.java:2096)
	at org.htmlunit.corejs.javascript.Parser.parse(Parser.java:302)
	at org.htmlunit.corejs.javascript.Context.parse(Context.java:2540)
	at org.htmlunit.corejs.javascript.Context.compileImpl(Context.java:2471)
	at org.htmlunit.corejs.javascript.Context.compileString(Context.java:1439)
	at org.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext.compileString(HtmlUnitContextFactory.java:220)
	at org.htmlunit.corejs.javascript.Context.compileString(Context.java:1427)
	at org.htmlunit.javascript.JavaScriptEngine$2.doRun(JavaScriptEngine.java:562)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:150)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:570)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:579)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:1)
	at org.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1152)
	at org.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1024)
	at org.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:194)
	at org.htmlunit.html.HtmlPage.executeDeferredScriptsIfNeeded(HtmlPage.java:1507)
	at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:280)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:686)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:568)
	at org.htmlunit.WebClient.getPage(WebClient.java:486)
	at org.htmlunit.WebClient.getPage(WebClient.java:393)
	at org.htmlunit.WebClient.getPage(WebClient.java:531)
	at org.htmlunit.WebClient.getPage(WebClient.java:513)
[https_--e-cdn-files.dzcdn.net-cache-js-app-backstage-plain-html.0271e60331cea69569bc.js.txt](https://github.com/HtmlUnit/htmlunit/files/13241634/https_--e-cdn-files.dzcdn.net-cache-js-app-backstage-plain-html.0271e60331cea69569bc.js.txt)

**Comment by JamesLee66** [comment]
I also encountered this problem

**Comment by JamesLee66** [comment]
May I ask if there is any good solution

**Comment by rbri** [comment]
seems to be a duplicate of https://github.com/HtmlUnit/htmlunit/issues/685

**Comment by rbri** [comment]
see #755
