### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.lang3.Range.of(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lorg/apache/commons/lang3/Range;

### ISSUE THREAD

**Issue by eljosemari** [HtmlUnit/htmlunit#660]
Hello,

In version 3.7 with commons-text-1.11.0.jar sometimes when execute method HtmlPage.asXml() I am getting this error:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.lang3.Range.of(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lorg/apache/commons/lang3/Range;
	at org.apache.commons.text.translate.NumericEntityEscaper.<init>(NumericEntityEscaper.java:97)
	at org.apache.commons.text.translate.NumericEntityEscaper.between(NumericEntityEscaper.java:59)
	at org.apache.commons.text.StringEscapeUtils.<clinit>(StringEscapeUtils.java:271)
	at org.htmlunit.html.HtmlTextArea.printXml(HtmlTextArea.java:459)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.printChildrenAsXml(DomNode.java:834)
	at org.htmlunit.html.DomElement.printXml(DomElement.java:350)
	at org.htmlunit.html.DomNode.asXml(DomNode.java:807)
	at org.htmlunit.SgmlPage.asXml(SgmlPage.java:211)

Rolling back from commons-text-1.11.0.jar to commons-text-1.10.0.jar it works again.

Thanks in advance.

**Comment by rbri** [comment]
I fear you have two versions of commons-lang in your classpath;
The missed method was added in version 3.13 - please make sure you only have the latest version in use.

**Comment by eljosemari** [comment]
Yes, I have checked and I have other referenced project with commons-lang3 dependency version 3.12. Thank you very much rbri

**Comment by rbri** [comment]
Great, have fun with HtmlUnit.

Github stars are welcome...;-)
