### ISSUE TITLE
JS error in execution page

### ISSUE THREAD

**Issue by JamesLee66** [HtmlUnit/htmlunit#685]
org.htmlunit.ScriptException: identifier is a reserved word: class (https://lf-cdn-tos.bytescm.com/obj/static/growth/douyin_ug/chunk/865.7b59e39c.js#2)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:1014)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:844)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:810)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:113)
	at org.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1152)
	at org.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1024)
	at org.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:194)
	at org.htmlunit.html.ScriptElementSupport$1.execute(ScriptElementSupport.java:118)
	at org.htmlunit.html.ScriptElementSupport.onAllChildrenAddedToPage(ScriptElementSupport.java:141)
	at org.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:192)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:599)
	at org.htmlunit.cyberneko.xerces.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:411)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:548)
	at org.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1270)
	at org.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1198)
	at org.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:201)
	at org.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:268)
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:2990)
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:1980)
	at org.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:814)
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:344)
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:302)
	at org.htmlunit.cyberneko.xerces.parsers.XMLParser.parse(XMLParser.java:72)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:842)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:202)
	at org.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:308)
	at org.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:227)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:671)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:573)
	at org.htmlunit.WebClient.getPage(WebClient.java:491)
	at org.htmlunit.WebClient.getPage(WebClient.java:398)
	at org.htmlunit.WebClient.getPage(WebClient.java:536)
	at org.htmlunit.WebClient.getPage(WebClient.java:518)

**Comment by rbri** [comment]
@JamesLee66 
Sorry but it looks like your are facing one of the major problems of Rhino - https://github.com/mozilla/rhino/issues/835.
At the moment there is no solution for that. I have some plans to overcome this but these are only plans so far.

Your options are
* disable js support - but i fear the page will no longer work for you
* ignore js errors (https://www.htmlunit.org/javascript-howto.html#Handling_of_JavaScript_errors), in some cases this works
* try to patch the js code on the fly by delivering a patched version of the js stuff (https://www.htmlunit.org/faq.html#HowToModifyRequestOrResponse)
* or ask your boss to pay me for implementing the support ;-)

**Comment by rbri** [comment]
see #755
