### ISSUE TITLE
getTopWindow() fails in Kotlin Sequences since version 3.6.0

### ISSUE THREAD

**Issue by jeffcjohnson** [HtmlUnit/htmlunit#686]
Hi, first off, love HtmlUnit, thanks for all you do!

The example code below works correctly in version 3.5.0 but fails in 3.6.0+ with the following exception:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.htmlunit.WebWindow.getTopWindow()" because the return value of "org.htmlunit.WebClient.getCurrentWindow()" is null
	at org.htmlunit.WebClient.getPage(WebClient.java:530)
	at org.htmlunit.WebClient.getPage(WebClient.java:512)
	at FooKt$extractRecords$2$records$1.invoke(foo.kt:23)
	at FooKt$extractRecords$2$records$1.invoke(foo.kt:22)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at FooKt.main(foo.kt:38)
	at FooKt.main(foo.kt)
```

```
import org.htmlunit.WebClient
import org.htmlunit.html.HtmlAnchor
import org.htmlunit.html.HtmlPage
import org.htmlunit.html.HtmlParagraph

private fun extractRecords(topUrl: String): Sequence<String> {
    WebClient()
        .apply {
            options.isCssEnabled = false
            options.isJavaScriptEnabled = false
        }
        .use { webClient ->
            val urls = webClient.getPage<HtmlPage>(topUrl)
                .getByXPath<HtmlAnchor>("//a")
                .asSequence()
                .mapNotNull { it.hrefAttribute }

            val records = urls.flatMap { url ->
                val page = webClient.getPage<HtmlPage>(url)
                page.getByXPath<HtmlParagraph>("//p")
                    .asSequence()
                    .map { it.asNormalizedText() }
            }

            return records
        }
}

fun main() {
    extractRecords("https://example.com")
        .forEach(::println)
}
```

**Comment by jeffcjohnson** [comment]
It looks like this might be a result of this change:

> INCOMPATIBLE CHANGE: WebClient.close() now really closes all windows and also stops the js engine. This means you can't use the the webClient afterwards for browsing. If you only like to cleanup all the window resources use WebClient.reset(). Fixes [627](https://github.com/HtmlUnit/htmlunit/issues/627).

So maybe the problem is in my use of sequences which are iterating over HtmlUnit resources after the use {} has closed them.

I'm going to close this ticket, assuming the problem is my use of sequences.  I'll be rewriting a lot of code :)

**Comment by rbri** [comment]
@jeffcjohnson sorry for that, if this is really related to the change we can discuss to do it better....

**Comment by jeffcjohnson** [comment]
I think it just highlights that my use of late evaluation of sequences after the webClient.use {} was wrong and I need to revisit my code.  I was using sequences to avoid processing very large numbers of records all in memory at the same time.  I think this rewrite of the sample code is more correct (though more complicated).

Honestly I've always wondered what magic was occuring that allowed it to work the way it did.

```
import org.htmlunit.WebClient
import org.htmlunit.html.HtmlAnchor
import org.htmlunit.html.HtmlPage
import org.htmlunit.html.HtmlParagraph

data class Record(
    val foo: String?,
)

private fun <R> extractRecords(topUrl: String, processRecords: Sequence<Record>.() -> R) : R {
    WebClient()
        .apply {
            options.isCssEnabled = false
            options.isJavaScriptEnabled = false
        }
        .use { webClient ->
            val urls = webClient.getPage<HtmlPage>(topUrl)
                .getByXPath<HtmlAnchor>("//a")
                .asSequence()
                .mapNotNull { it.hrefAttribute }

            val records: Sequence<Record> = urls.flatMap { url ->
                val page = webClient.getPage<HtmlPage>(url)
                page.getByXPath<HtmlParagraph>("//p")
                    .asSequence()
                    .map { Record(foo = it.asNormalizedText()) }
            }

            return records.processRecords()
        }
}

private fun Sequence<Record>.printRecords() {
    forEach(::println)
}

fun main() {
    extractRecords("https://example.com", Sequence<Record>::printRecords)
    extractRecords("https://example.com", Sequence<Record>::toList).forEach(::println)
}

```
