### ISSUE TITLE
NoSuchFileException when trying to get page

### ISSUE THREAD

**Issue by owochle** [HtmlUnit/htmlunit#696]
I get a NoSuchFileException when trying to query a page. The only guess i have would be that it is unable to write in /tmp, which is weird. Here is the traceback
```java
17:55:00 WARN org.htmlunit.WebResponse | /tmp/htmlunit15014647045775338636.tmp
java.nio.file.NoSuchFileException: /tmp/htmlunit15014647045775338636.tmp
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.base/java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at org.htmlunit.DownloadedContent$OnFile.getInputStream(DownloadedContent.java:89) ~[htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebResponseData.getStream(WebResponseData.java:97) ~[htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebResponseData.getInputStreamWithBomIfApplicable(WebResponseData.java:218) ~[htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebResponse.getContentAsString(WebResponse.java:265) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.util.WebResponseWrapper.getContentAsString(WebResponseWrapper.java:96) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1146) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1023) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:194) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.ScriptElementSupport$1.execute(ScriptElementSupport.java:118) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.ScriptElementSupport.onAllChildrenAddedToPage(ScriptElementSupport.java:141) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:192) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:599) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.xerces.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:412) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:548) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1270) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1198) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:201) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:269) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:2938) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:1923) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:813) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:319) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:277) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.cyberneko.xerces.parsers.XMLParser.parse(XMLParser.java:73) [neko-htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:842) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:202) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:301) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:220) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:665) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:567) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebClient.getPage(WebClient.java:485) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebClient.getPage(WebClient.java:392) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebClient.getPage(WebClient.java:530) [htmlunit-3.6.0.jar:3.6.0]
	at org.htmlunit.WebClient.getPage(WebClient.java:512) [htmlunit-3.6.0.jar:3.6.0]
	at session.LoginKt.login(Login.kt:30) [main/:?]
	at views.TenantsKt$Tenants$1$1.invokeSuspend(Tenants.kt:34) [main/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.9.21.jar:1.9.21-release-633]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:800) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:704) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:691) [kotlinx-coroutines-core-jvm-1.8.0-RC.jar:?]
```

**Comment by rbri** [comment]
@OwOchlee funny i guess i have an idea but not a real fix. Will require some time to figure out what goes wrong here.

But as a possible workaround please try 

    webClient.getOptions().setMaxInMemory(Integer.MAX_VALUE);

Please try and please inform about the results.

**Comment by rbri** [comment]
btw do you use the latest version?

**Comment by owochle** [comment]
I wasn't, but it's not working with the latest version either (after upgrading, cleaning and restarting).

**Comment by rbri** [comment]
> I wasn't, but it's not working with the latest version either (after upgrading, cleaning and restarting).

i did not expect any change with the latest version but i have big hopes for the workaround....

**Comment by owochle** [comment]
The workaround does work, thanks

**Comment by rbri** [comment]
@OwOchlee great, can i please come back to you if i have a real fix for testing in the wild?

**Comment by owochle** [comment]
Sure !

**Comment by rbri** [comment]
@OwOchlee

have done some code review but i did not really found an idea why this fails for you.
* can you please try with the latest snapshot build?
* if the snapshot still fails (what i expect) - do you see a chance to debug this at your side or give me enough info (maybe on a private channel) to do it here?

**Comment by rbri** [comment]
no feedback will close this (but i fear we will face this again)
