### ISSUE TITLE
From version 3.6.0 until now i cant get page in thread

### ISSUE THREAD

**Issue by augusto-f-fonseca-alpt** [HtmlUnit/htmlunit#701]
From version 3.6.0 until now i am unable to get page in thread, i have null pointer exception, for example:

Main.java:
```
package htmlunitexample;

import org.htmlunit.BrowserVersion;
import org.htmlunit.WebClient;

public class HtmlUnitExample {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String url = "https://www.google.pt";
        BrowserVersion bv = new BrowserVersion.BrowserVersionBuilder(BrowserVersion.CHROME).setUserAgent("Test").build();
        try (WebClient webClient = new WebClient(bv)){
            ThreadExample te = new ThreadExample(webClient, url);
            te.start();
        }
    }
}
```

ThreadExample.java:
```
package htmlunitexample;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.Charset;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.apache.http.HttpStatus;
import org.apache.http.client.utils.URIBuilder;
import org.htmlunit.FailingHttpStatusCodeException;
import org.htmlunit.HttpMethod;
import org.htmlunit.WebClient;
import org.htmlunit.WebRequest;
import org.htmlunit.WebResponse;

public class ThreadExample extends Thread{
    private final WebClient webClientInst;
    private final String url;
    
    public ThreadExample(WebClient webClient, String url){
        this.webClientInst = webClient;
        this.url = url;
    }
    
    @Override
    public void run(){
        try{
            URIBuilder builder = new URIBuilder(this.url);
            WebRequest requestSettings = new WebRequest(builder.build().toURL(),HttpMethod.valueOf("GET"));
            //this.webClientInst.reset();
            WebResponse webResp = this.webClientInst.getPage(requestSettings).getWebResponse();
            if( webResp.getStatusCode() == HttpStatus.SC_OK) {
                String httpResponse = webResp.getContentAsString(Charset.forName("UTF-8"));
                //httpResponse = httpResponse.replaceAll("\n", " ");
                System.out.println("Received success from request, http response:\n" + httpResponse);
            }else{
                System.out.println("Failed to send request (HTTP Status > " + webResp.getStatusCode() + ":" + webResp.getStatusMessage());
            }
        }catch(IOException | URISyntaxException | FailingHttpStatusCodeException ex){
            System.out.println("Error: " + ExceptionUtils.getStackTrace(ex));
        }
    }
}
```

And i have the error:
```
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.htmlunit.WebClient.getPage(WebClient.java:551)
	at htmlunitexample.ThreadExample.run(ThreadExample.java:30)
```

What i see, currentWindow_  becames true after i pass the webclient instance to the thread and that is the problem, of course if i execute de condition the problem is resolved:
```
this.webClientInst.reset();
```

My question is, is supposed to be this way, or i am using this in the wrong way?

**Comment by rbri** [comment]
Hi @augusto-f-fonseca-alpt,

i think your code is wrong :-D

    try (WebClient webClient = new WebClient(bv)){
        ThreadExample te = new ThreadExample(webClient, url);
        te.start();
    }

This means the webClient gets closed (and not usable any longer afterwards) as soon as you left the try block. If you start a thread inside the block using the webClient, this thread might access the client after the client is already closed.

Simple solution:

    try (WebClient webClient = new WebClient(bv)){
        ThreadExample te = new ThreadExample(webClient, url);
        te.start();

        te.join(); // wait until the thread has finished
    }

But i guess in your real application you have to fight a bit harder to make sure to close the client after all work is done.

**Comment by augusto-f-fonseca-alpt** [comment]
Hi, you are right, thanks for opening my eyes for that aspect.

**Comment by rbri** [comment]
Your welcome, and thanks for using HtmlUnit.
