### ISSUE TITLE
`org.htmlunit.corejs.javascript.EcmaError` on Java 11

### ISSUE THREAD

**Issue by basil** [HtmlUnit/htmlunit#714]
After upgrading to HtmlUnit 3.10.0 we started seeing failures in https://github.com/jenkinsci/jenkins in the following two tests, only on Java 11:

- `hudson.model.ManagementLinkTest.links`
- `jenkins.widgets.BuildTimeTrendTest.withAbstractJob_OnBoth`

The failures do not occur on Java 17 and Java 21, and they do not occur on HtmlUnit 3.9.0.

I reproduced one of these failures locally on Java 11 by running `mvn clean verify -Dtest=jenkins.widgets.BuildTimeTrendTest#withAbstractJob_OnBuiltInNode,hudson.model.ManagementLinkTest#links` against jenkinsci/jenkins@8aa627660907d3a15b9d7e23de01eaed6071bf41.

As in #602 and #669, we have rolled back to 3.9.0 in jenkinsci/jenkins@dbd5f115ad67542592af0a72bb21bebd77b1bf86.

```
======= EXCEPTION START ========
EcmaError: lineNumber=[3] column=[0] lineSource=[] name=[TypeError] sourceName=[http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js] message=[TypeError: Cannot call method "querySelector" of null (http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js#3)]
org.htmlunit.ScriptException: TypeError: Cannot call method "querySelector" of null (http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js#3)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:1003)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:930)
	at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:903)
	at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2599)
	at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2592)
	at org.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:340)
	at org.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:377)
	at org.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:177)
	at org.htmlunit.html.HtmlPage.lambda$executeEventHandlersIfNeeded$1(HtmlPage.java:1305)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1305)
	at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:280)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:691)
	at org.htmlunit.WebClient.loadDownloadedResponses(WebClient.java:2763)
	at org.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:1031)
	at org.htmlunit.javascript.JavaScriptEngine.processPostponedActions(JavaScriptEngine.java:1157)
	at org.htmlunit.html.DomElement.click(DomElement.java:1115)
	at org.htmlunit.html.HtmlAnchor.click(HtmlAnchor.java:87)
	at org.htmlunit.html.DomElement.click(DomElement.java:1046)
	at org.htmlunit.html.DomElement.click(DomElement.java:932)
	at org.htmlunit.html.DomElement.click(DomElement.java:909)
	at org.htmlunit.html.DomElement.click(DomElement.java:886)
	at hudson.model.ManagementLinkTest.links(ManagementLinkTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot call method "querySelector" of null (http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js#3)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4665)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4646)
	at org.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4678)
	at org.htmlunit.corejs.javascript.ScriptRuntime.typeErrorById(ScriptRuntime.java:4683)
	at org.htmlunit.corejs.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:4719)
	at org.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2632)
	at org.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2626)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1661)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051)
	at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
	at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:389)
	at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:333)
	at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3946)
	at org.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:923)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:986)
	... 31 more
Enclosed exception: 
org.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot call method "querySelector" of null (http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js#3)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4665)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4646)
	at org.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4678)
	at org.htmlunit.corejs.javascript.ScriptRuntime.typeErrorById(ScriptRuntime.java:4683)
	at org.htmlunit.corejs.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:4719)
	at org.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2632)
	at org.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2626)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1661)
	at script.initializeAmMonitor(http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js:3)
	at script(http://localhost:40687/jenkins/adjuncts/e77dab99/jenkins/management/AdministrativeMonitorsDecorator/resources.js:86)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051)
	at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
	at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:389)
	at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:333)
	at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3946)
	at org.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:923)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:986)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:930)
	at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:903)
	at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2599)
	at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2592)
	at org.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:340)
	at org.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:377)
	at org.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:177)
	at org.htmlunit.html.HtmlPage.lambda$executeEventHandlersIfNeeded$1(HtmlPage.java:1305)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1305)
	at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:280)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:691)
	at org.htmlunit.WebClient.loadDownloadedResponses(WebClient.java:2763)
	at org.htmlunit.javascript.JavaScriptEngine.doProcessPostponedActions(JavaScriptEngine.java:1031)
	at org.htmlunit.javascript.JavaScriptEngine.processPostponedActions(JavaScriptEngine.java:1157)
	at org.htmlunit.html.DomElement.click(DomElement.java:1115)
	at org.htmlunit.html.HtmlAnchor.click(HtmlAnchor.java:87)
	at org.htmlunit.html.DomElement.click(DomElement.java:1046)
	at org.htmlunit.html.DomElement.click(DomElement.java:932)
	at org.htmlunit.html.DomElement.click(DomElement.java:909)
	at org.htmlunit.html.DomElement.click(DomElement.java:886)
	at hudson.model.ManagementLinkTest.links(ManagementLinkTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
== CALLING JAVASCRIPT ==
function () {
    var monitorWidgets;

    function closeAll() {
      monitorWidgets.forEach(function (widget) {
        widget.close();
      });
    }

    var normalMonitors = initializeAmMonitor(
      document.getElementById("visible-am-container"),
      {
        closeAll: closeAll,
      },
    );
    var securityMonitors = initializeAmMonitor(
      document.getElementById("visible-sec-am-container"),
      {
        closeAll: closeAll,
      },
    );
    monitorWidgets = [normalMonitors, securityMonitors].filter(
      function (widget) {
        return widget !== null;
      },
    );

    monitorWidgets.forEach(function (widget) {
      widget.startListeners();
    });
  }
======= EXCEPTION END ========
```

and

```
======= EXCEPTION START ========
EcmaError: lineNumber=[38] column=[0] lineSource=[<no source>] name=[ReferenceError] sourceName=[script in http://localhost:34703/jenkins/job/test0/buildTimeTrend from (38, 362) to (38, 482)] message=[ReferenceError: "makeStaplerProxy" is not defined. (script in http://localhost:34703/jenkins/job/test0/buildTimeTrend from (38, 362) to (38, 482)#38)]
org.htmlunit.ScriptException: ReferenceError: "makeStaplerProxy" is not defined. (script in http://localhost:34703/jenkins/job/test0/buildTimeTrend from (38, 362) to (38, 482)#38)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:1003)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:882)
	at org.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:858)
	at org.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:849)
	at org.htmlunit.html.HtmlPage.executeJavaScript(HtmlPage.java:968)
	at org.htmlunit.html.ScriptElementSupport.executeInlineScriptIfNeeded(ScriptElementSupport.java:377)
	at org.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:227)
	at org.htmlunit.html.ScriptElementSupport$1.execute(ScriptElementSupport.java:117)
	at org.htmlunit.html.ScriptElementSupport.onAllChildrenAddedToPage(ScriptElementSupport.java:140)
	at org.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:192)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:591)
	at org.htmlunit.cyberneko.xerces.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:399)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:540)
	at org.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1263)
	at org.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1195)
	at org.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:201)
	at org.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:268)
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3183)
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:1942)
	at org.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:818)
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:336)
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:294)
	at org.htmlunit.cyberneko.xerces.parsers.XMLParser.parse(XMLParser.java:72)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:834)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:202)
	at org.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:308)
	at org.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:227)
	at org.jvnet.hudson.test.HudsonPageCreator.createPage(HudsonPageCreator.java:53)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:671)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:573)
	at org.htmlunit.WebClient.getPage(WebClient.java:491)
	at org.htmlunit.WebClient.getPage(WebClient.java:398)
	at org.htmlunit.WebClient.getPage(WebClient.java:536)
	at org.htmlunit.WebClient.getPage(WebClient.java:518)
	at org.jvnet.hudson.test.JenkinsRule$WebClient.goTo(JenkinsRule.java:2722)
	at org.jvnet.hudson.test.JenkinsRule$WebClient.goTo(JenkinsRule.java:2702)
	at org.jvnet.hudson.test.JenkinsRule$WebClient.getPage(JenkinsRule.java:2657)
	at jenkins.widgets.BuildTimeTrendTest.withAbstractJob_OnBoth(BuildTimeTrendTest.java:116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.htmlunit.corejs.javascript.EcmaError: ReferenceError: "makeStaplerProxy" is not defined. (script in http://localhost:34703/jenkins/job/test0/buildTimeTrend from (38, 362) to (38, 482)#38)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4665)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4646)
	at org.htmlunit.corejs.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4734)
	at org.htmlunit.corejs.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2534)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1649)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051)
	at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
	at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:389)
	at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:333)
	at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3946)
	at org.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:102)
	at org.htmlunit.javascript.JavaScriptEngine$2.doRun(JavaScriptEngine.java:873)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:986)
	... 44 more
Enclosed exception: 
org.htmlunit.corejs.javascript.EcmaError: ReferenceError: "makeStaplerProxy" is not defined. (script in http://localhost:34703/jenkins/job/test0/buildTimeTrend from (38, 362) to (38, 482)#38)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4665)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4646)
	at org.htmlunit.corejs.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4734)
	at org.htmlunit.corejs.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2534)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1649)
	at script(script in http://localhost:34703/jenkins/job/test0/buildTimeTrend from (38, 362) to (38, 482):38)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051)
	at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
	at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:389)
	at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:333)
	at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3946)
	at org.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:102)
	at org.htmlunit.javascript.JavaScriptEngine$2.doRun(JavaScriptEngine.java:873)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:986)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:581)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:481)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:347)
	at org.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:882)
	at org.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:858)
	at org.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:849)
	at org.htmlunit.html.HtmlPage.executeJavaScript(HtmlPage.java:968)
	at org.htmlunit.html.ScriptElementSupport.executeInlineScriptIfNeeded(ScriptElementSupport.java:377)
	at org.htmlunit.html.ScriptElementSupport.executeScriptIfNeeded(ScriptElementSupport.java:227)
	at org.htmlunit.html.ScriptElementSupport$1.execute(ScriptElementSupport.java:117)
	at org.htmlunit.html.ScriptElementSupport.onAllChildrenAddedToPage(ScriptElementSupport.java:140)
	at org.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:192)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:591)
	at org.htmlunit.cyberneko.xerces.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:399)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.endElement(HtmlUnitNekoDOMBuilder.java:540)
	at org.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1263)
	at org.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1195)
	at org.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:201)
	at org.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:268)
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3183)
	at org.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:1942)
	at org.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:818)
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:336)
	at org.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:294)
	at org.htmlunit.cyberneko.xerces.parsers.XMLParser.parse(XMLParser.java:72)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoDOMBuilder.parse(HtmlUnitNekoDOMBuilder.java:834)
	at org.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.parse(HtmlUnitNekoHtmlParser.java:202)
	at org.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:308)
	at org.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:227)
	at org.jvnet.hudson.test.HudsonPageCreator.createPage(HudsonPageCreator.java:53)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:671)
	at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:573)
	at org.htmlunit.WebClient.getPage(WebClient.java:491)
	at org.htmlunit.WebClient.getPage(WebClient.java:398)
	at org.htmlunit.WebClient.getPage(WebClient.java:536)
	at org.htmlunit.WebClient.getPage(WebClient.java:518)
	at org.jvnet.hudson.test.JenkinsRule$WebClient.goTo(JenkinsRule.java:2722)
	at org.jvnet.hudson.test.JenkinsRule$WebClient.goTo(JenkinsRule.java:2702)
	at org.jvnet.hudson.test.JenkinsRule$WebClient.getPage(JenkinsRule.java:2657)
	at jenkins.widgets.BuildTimeTrendTest.withAbstractJob_OnBoth(BuildTimeTrendTest.java:116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
======= EXCEPTION END ========
```

**Comment by rbri** [comment]
@basil I'm able to reproduce this here ... will try to figure out what is going wrong

**Comment by rbri** [comment]
after some hours of testing i have a first idea what might go wrong here, have to write some tests

**Comment by rbri** [comment]
@basil can you please give me a hint how to run the project with a different HtmlUnit version

**Comment by basil** [comment]
See https://github.com/jenkinsci/jenkins-test-harness-htmlunit/pull/133, https://github.com/jenkinsci/jenkins-test-harness/pull/686, and https://github.com/jenkinsci/jenkins/pull/8715.

**Comment by rbri** [comment]
What i know so far:

* a more simpler command line produces the result here also `mvn clean verify -Dtest=jenkins.widgets.BuildTimeTrendTest#withAbstractJob_OnBuiltInNode -Dcheckstyle.skip -Dspotbugs.skip -Dspotless.skip`
* the tested page includes many artifacts, mainly css files and js files
* for the test itself javascript support is not required - simply disabling js for the webclient makes the test passing
* the problematic part is this script tag `<script src="/adjuncts/7e34e070/org/kohsuke/stapler/bind.js" type="text/javascript"></script>`; this tag includes the missing function 'makeStaplerProxy'
* have patched the code to get some more output
  * looks like there is something broken while parsing the tag before; dumping the html of the page asXml() shows a starting CDATA session before the closing script tag of the script tag before
  * this lead to a commented script tag for bind.js - and therefore the js is not downloaded and the funktion is missing afterwards

**Comment by rbri** [comment]
lookd like this does not always fail - sometimes this passes

**Comment by rschwietzke** [comment]
@rbri Just a feeling. Increase the scanner buffer size   `protected static final int DEFAULT_BUFFER_SIZE = (10 * 64) - 24;`  in `HtmlScanner` to the original 2048. I noticed, why playing around, that certain buffer sizes make things fail, which is not correct and explainable. Not necessarily only too small but sometimes also certain sizes. The large buffer seems to push that problem out but it is not nice to the CPU cache, hence smaller is better.

**Comment by rschwietzke** [comment]
Buffer size 100-105 fails Neko testing, 106 works (JDK 11, 17).

By the way, JDK 17 and 21 deliver new Unicode implementations, maybe that explains the difference when running because some encoding is different, might not be in that code in question but before.

**Comment by rbri** [comment]
@rschwietzke fantastic - can reproduce this here

**Comment by rbri** [comment]
ok, the failing test i see here is because of this impl

This seems to be some kind of lookahead (but only inside the buffer_ to check for the existence of an end tag. As always with lookahead - more is better.

        /**
         * Returns true if the given element has an end-tag.
         */
        private boolean isEnded(final String ename) {
            final String content = new String(fCurrentEntity.buffer_, fCurrentEntity.offset_,
                    fCurrentEntity.length_ - fCurrentEntity.offset_);
            return content.toLowerCase(Locale.ROOT).contains("</" + ename.toLowerCase(Locale.ROOT) + ">");
        }

**Comment by rschwietzke** [comment]
Does the larger buffer make the Jenkins problem go away? In any case, I would put that `isEnded` thing on my table to review, fix, and tune it. Can you make it a ticket for me?

**Comment by rbri** [comment]
Have fixed the buffer size problem by removing the call to isEnded completely. This also brings the parser closer to the spec.

**Comment by rbri** [comment]
> Does the larger buffer make the Jenkins problem go away?

not tested so far

**Comment by rbri** [comment]
@basil was still not able to nail down the problem

But there are already many fixes for HtmlUnit and Neko. Will do a release over the weekend. Please do not update to this, will investigate further and report about the progress here.

**Comment by rbri** [comment]
@basil looks like we facing something similar in another environment, lets hope this helps to understand the problem

**Comment by rschwietzke** [comment]
So far, I condensed it down to CDATA, script, and some comments but don't know yet, why it is not predictable but rather random.

**Comment by rbri** [comment]
see https://github.com/HtmlUnit/htmlunit-neko/pull/98 - i'm really sure this pr is the solution for this also as i have seen exactly the same misbehavior here.

**Comment by basil** [comment]
We have successfully upgraded to 4.0.0, where this issue is resolved. Thank you very much!

**Comment by rbri** [comment]
@basil great to see, thanks for the feedback
