### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.commons.io.ByteOrderMark

### ISSUE THREAD

**Issue by freddyfeng-fy** [HtmlUnit/htmlunit#73]
严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/io/ByteOrderMark] with root cause
java.lang.ClassNotFoundException: org.apache.commons.io.ByteOrderMark
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.gargoylesoftware.htmlunit.WebResponse.<clinit>(WebResponse.java:52)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.newWebResponseInstance(HttpWebConnection.java:763)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.makeWebResponse(HttpWebConnection.java:687)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:215)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1402)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1321)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:394)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:315)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:466)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:448)
	at com.feng.service.impl.WebmagicServiceImpl.nextACGVideo(WebmagicServiceImpl.java:59)
	at com.feng.controller.WebmagicConllor.nextACGVideo(WebmagicConllor.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

WebClient webClient = new WebClient(BrowserVersion.CHROME);
transfer function webClient.getPage("url") appeared;

**Comment by rbri** [comment]
Am 31. August 2019 10:50:22 MESZ schrieb fy976061258 <notifications@github.com>:
>严重: Servlet.service() for servlet [dispatcherServlet] in context with
>path [] threw exception [Handler dispatch failed; nested exception is
>java.lang.NoClassDefFoundError: org/apache/commons/io/ByteOrderMark]
>with root cause>
>java.lang.ClassNotFoundException: org.apache.commons.io.ByteOrderMark>
>	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)>
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)>
>	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)>
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)>
>	at
>com.gargoylesoftware.htmlunit.WebResponse.<clinit>(WebResponse.java:52)>
>	at
>com.gargoylesoftware.htmlunit.HttpWebConnection.newWebResponseInstance(HttpWebConnection.java:763)>
>	at
>com.gargoylesoftware.htmlunit.HttpWebConnection.makeWebResponse(HttpWebConnection.java:687)>
>	at
>com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:215)>
>	at
>com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1402)>
>	at
>com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1321)>
>	at
>com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:394)>
>	at
>com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:315)>
>	at
>com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:466)>
>	at
>com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:448)>
>	at
>com.feng.service.impl.WebmagicServiceImpl.nextACGVideo(WebmagicServiceImpl.java:59)>
>	at
>com.feng.controller.WebmagicConllor.nextACGVideo(WebmagicConllor.java:28)>
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)>
>	at
>sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)>
>	at
>sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)>
>	at java.lang.reflect.Method.invoke(Method.java:498)>
>	at
>org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)>
>	at
>org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)>
>	at
>org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)>
>	at
>org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)>
>	at
>org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)>
>	at
>org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)>
>	at
>org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)>
>	at
>org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)>
>	at
>org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)>
>	at
>org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)>
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)>
>	at
>org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)>
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)>
>	at
>org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)>
>	at
>org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)>
>	at
>org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)>
>	at
>org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)>
>	at
>org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)>
>	at
>org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)>
>	at
>org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)>
>	at
>org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)>
>	at
>org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)>
>	at
>org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)>
>	at
>org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)>
>	at
>org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)>
>	at
>org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)>
>	at
>org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)>
>	at
>org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)>
>	at
>org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)>
>	at
>org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)>
>	at
>org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)>
>	at
>org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)>
>	at
>org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)>
>	at
>org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)>
>	at
>org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)>
>	at
>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)>
>	at
>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)>
>	at
>org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)>
>	at java.lang.Thread.run(Thread.java:745)>
>>
>WebClient webClient = new WebClient(BrowserVersion.CHROME);>
>transfer function webClient.getPage("url") appeared;>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/HtmlUnit/htmlunit/issues/73

Please check your classpath for a commons-io doplicate or incorrect version.

**Comment by freddyfeng-fy** [comment]
> Am 31. August 2019 10:50:22 MESZ schrieb fy976061258 <notifications@github.com>：
> 严重：servlet [dispatcherServlet]的Servlet.service（）与path []的上下文引发了异常[Handler dispatch failed; 嵌套异常是java.lang.NoClassDefFoundError：org / apache / commons / io / ByteOrderMark]，根本原因> java.lang.ClassNotFoundException：org.apache.commons.io.ByteOrderMark> at java.net.URLClassLoader.findClass（URLClassLoader。 java：381）> at java.lang.ClassLoader.loadClass（ClassLoader.java:424）> at sun.misc.Launcher $ AppClassLoader.loadClass（Launcher.java:331）> at java.lang.ClassLoader.loadClass（ClassLoader。 java：357）> at com.gargoylesoftware.htmlunit.WebResponse。<clinit>（WebResponse.java:52）> at com.gargoylesoftware.htmlunit.HttpWebConnection.newWebResponseInstance（HttpWebConnection.java:763）> at com.gargoylesoftware.htmlunit。 HttpWebConnection.makeWebResponse（HttpWebConnection.java:687）> [＃73](https://github.com/HtmlUnit/htmlunit/issues/73)
> 请检查您的类路径以查找commons-io doplicate或不正确的版本。

thanks resolved.
Add to pom.xml.
<dependency>
       <groupId>commons-io</groupId>
       <artifactId>commons-io</artifactId>
       <version>2.4</version>
</dependency>
