### ISSUE TITLE
 HtmlUnit 3.11.0 :  Sill 1 top level windows are open. Please report this error! 

### ISSUE THREAD

**Issue by qurikuduo** [HtmlUnit/htmlunit#730]
This is what I do in my code using HtmlUnit 3.11.0 :

```
      try (WebClient webClient = new WebClient(BrowserVersion.FIREFOX);) {
            try{
                webClient.getOptions().setJavaScriptEnabled(jsFlag);
                webClient.getOptions().setCssEnabled(cssFlag);
                webClient.getOptions().setUseInsecureSSL(true);              
                webClient.setJavaScriptErrorListener(new SilentJavaScriptErrorListener());
                webClient.getOptions().setPrintContentOnFailingStatusCode(false);
                webClient.setCssErrorHandler(new SilentCssErrorHandler());
                webClient.setJavaScriptErrorListener(new SilentJavaScriptErrorListener());
                webClient.setAjaxController(new NicelyResynchronizingAjaxController());
                webClient.getOptions().setTimeout(25 * 1000);
                webClient.getOptions().setPopupBlockerEnabled(false);
                webClient.getOptions().setRedirectEnabled(true);
                webClient.getOptions().setUseInsecureSSL(true);
                webClient.getOptions().setThrowExceptionOnScriptError(false);
                webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
                webClient.addRequestHeader("Accept-Language", "zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4");
                webClient.getCookieManager().setCookiesEnabled(true);
                
                url = "http://www.jiyuan.gov.cn"
                HtmlPage page = null;
                page = webClient.getPage(url);
                // some other logic process such as extract Text from html etc. 

             } catch (Exception e) {
                 logger.error(e);
             } finally {
                try {
                    webClient.getJavaScriptEngine().shutdown();
                    webClient.close();
                } catch (Exception e) {
                    logger.error("close webClient error", e);
                }
            }
       }
```
Then I got the error log as below:

Feb 20, 2024 10:59:32 am org.htmlunit.WebClient close
 Exception while closing a TopLevelWindow
java.lang.NullPointerException
	at org.htmlunit.html.HtmlPage.executeEventHandlersIfNeeded(HtmlPage.java:1303)
	at org.htmlunit.html.HtmlPage.cleanUp(HtmlPage.java:372)
	at org.htmlunit.TopLevelWindow.close(TopLevelWindow.java:144)
	at org.htmlunit.WebClient.close(WebClient.java:2348)

Feb 20, 2024 10:59:32 am org.htmlunit.WebClient close
 Sill 1 top level windows are open. Please report this error!

I don't know what the problem is. I'm trying to figure it out, but I haven't made any progress yet. Any suggestions would be hugely helpful. Thanks a lot.

**Comment by rbri** [comment]
@qurikuduo many thanks for this report, will try to reproduce this at the end of the week.

**Comment by rbri** [comment]
@qurikuduo webClient.close(); will shutdown the js engine also - there is no need to do it before.
But if you do it, there was some code that tries to trigger the onClose event and this code did not check for the already gone js engine.
This is fixed now and you can use the latest 3.12.0-SNAPSHOT

Thanks for reporting....

**Comment by qurikuduo** [comment]
> @qurikuduo webClient.close(); will shutdown the js engine also - there is no need to do it before. But if you do it, there was some code that tries to trigger the onClose event and this code did not check for the already gone js engine. This is fixed now and you can use the latest 3.12.0-SNAPSHOT
> 
> Thanks for reporting....

Oh, Thank you very much!
I was updated HtmlUnit from 2.47.1 to 3.11.0 yesterday.

**Comment by rbri** [comment]
@qurikuduo does it work for you now? Can i close this?

**Comment by qurikuduo** [comment]
Seems works 

> @qurikuduo does it work for you now? Can i close this?

```
16:49:03.422 [main] DEBUG org.htmlunit.html.HtmlPage - Firing Event beforeunload (Current Target: org.htmlunit.javascript.host.html.HTMLDocument@688d411b);
16:49:03.422 [main] INFO org.htmlunit.javascript.JavaScriptEngine - execute() called after the shutdown of the Javascript engine and therefore not processed
16:49:03.422 [main] DEBUG org.htmlunit.html.HtmlPage - Firing Event unload (Current Target: org.htmlunit.javascript.host.html.HTMLDocument@688d411b);
16:49:03.422 [main] INFO org.htmlunit.javascript.JavaScriptEngine - execute() called after the shutdown of the Javascript engine and therefore not processed
16:49:03.422 [main] DEBUG org.htmlunit.WebWindowImpl - destroyChildren
16:49:03.422 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager is shutting down
16:49:03.423 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-22: Close connection
16:49:03.423 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-17: Close connection
16:49:03.423 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-16: Close connection
16:49:03.424 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-1: Close connection
16:49:03.424 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-15: Close connection
16:49:03.424 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-14: Close connection
16:49:03.424 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-18: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-9: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-23: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-12: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-11: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-10: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-3: Close connection
16:49:03.425 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-2: Close connection
16:49:03.426 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager shut down

Process finished with exit code 0

```
@rbri Sorry for my delay, 3.12.0-SNAPSHOT works great. Thank you very much. 
I'll close it immediately.
