### ISSUE TITLE
NPE when JavaScript engine disabled

### ISSUE THREAD

**Issue by jowerner** [HtmlUnit/htmlunit#798]
Hi! We are currently testing the new 4.x line of HtmlUnit with the latest version 4.2.0. When running a scenario with the JavaScript engine disabled, we encountered a NullPointerException:

```
java.lang.NullPointerException
	at org.htmlunit.html.DomElement.click(DomElement.java:1005)
	at org.htmlunit.html.DomElement.click(DomElement.java:939)
	at org.htmlunit.html.DomElement.click(DomElement.java:916)
	at org.htmlunit.html.DomElement.click(DomElement.java:893)
	at DomElementClickWithJavaScriptEngineDisabledTest.test(DomElementClickWithJavaScriptEngineDisabledTest.java:23)
```

Maybe we need some more checks in the click() method before invoking the JavaScript engine.

**Comment by rbri** [comment]
Hi @jowerner,
that migt be correct... 😁
Correnty I'm on vacation, will be back at the end of the week and will have a look. 
And as always, test cases are welcome.

**Comment by jowerner** [comment]
All right, thank you. Enjoy your vacation! 😃

**Comment by rbri** [comment]
should be fixed now, please try the latest snapshot.

**Comment by jowerner** [comment]
Yup, works now. 👍 
Thanks a lot for fixing this so quickly while you're on vacation!

**Comment by rbri** [comment]
Great, thanks.
