### ISSUE TITLE
 Bad language version: 200

### ISSUE THREAD

**Issue by G5513** [HtmlUnit/htmlunit#87]
Exception in thread "main" java.lang.IllegalArgumentException: Bad language version: 200

at net.sourceforge.htmlunit.corejs.javascript.Context.checkLanguageVersion(Context.java:798)
at net.sourceforge.htmlunit.corejs.javascript.Context.setLanguageVersion(Context.java:768)
at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.makeContext(HtmlUnitContextFactory.java:275)
at net.sourceforge.htmlunit.corejs.javascript.Context.enter(Context.java:537)
at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:635)
at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:518)
at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.initialize(JavaScriptEngine.java:168)
at com.gargoylesoftware.htmlunit.WebClient.initialize(WebClient.java:1084)
at com.gargoylesoftware.htmlunit.WebWindowImpl.setEnclosedPage(WebWindowImpl.java:134)
at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:212)
at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:190)
at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:269)
at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:160)
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:534)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:400)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:317)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:469)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:450)
at com.same.htmlunit.HtmlUnitTest.work(HtmlUnitTest.java:59)
at com.same.htmlunit.HtmlUnitTest.main(HtmlUnitTest.java:82)

  HtmlUnitContextFactory.TimeoutContext cx = new HtmlUnitContextFactory.TimeoutContext(this);
        cx.setLanguageVersion(200);
        cx.setOptimizationLevel(-1);
        cx.setInstructionObserverThreshold(10000);
        cx.setErrorReporter(new HtmlUnitContextFactory.HtmlUnitErrorReporter(this.webClient_.getJavaScriptErrorListener()));
        cx.setWrapFactory(this.wrapFactory_);
        if (this.debugger_ != null) {
            cx.setDebugger(this.debugger_, (Object)null);
        }

version is set by sourcecode， i hava something not done ？ i donot kown。

can you tell me why ？ thanks。

**Comment by rbri** [comment]
What version do you use?

Please make sure you have the proper core-js.jar in your classpath (check for duplicates also)

**Comment by G5513** [comment]
thanks  ，i have solved it，it is my selenium  cause this problem ，thank you very much。

**Comment by hanelalo** [comment]
打扰一下，请问您是怎么解决的？我遇见了同样的问题

**Comment by Ade5954** [comment]
> 打扰一下，请问您是怎么解决的？我遇见了同样的问题

https://github.com/SeleniumHQ/htmlunit-driver
