### ISSUE TITLE
HTMX 2.0.3 fails with a  syntax error on htmx.js line 1467

### ISSUE THREAD

**Issue by mzeijen** [HtmlUnit/htmlunit#891]
I tried upgrading to HTMX 2.0.3, using HTMLUnit 4.5.0 and I hit the following error:

```
Exception class=[org.htmlunit.corejs.javascript.EvaluatorException]
org.htmlunit.ScriptException: syntax error (http://localhost:59068/internal/assets/webjars/htmx.org/2.0.3/dist/htmx.js#1467)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:903)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:590)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:487)
	at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:316)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:734)
	at org.htmlunit.javascript.JavaScriptEngine.compile(JavaScriptEngine.java:109)
	at org.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1124)
        ...
```

It seems to have an issue with the following [line](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1467):

```
for (const preservedElt of [...pantry.children]) {
```

I can confirm that HTMX 2.0.2 does not have this issue and HTMLUnit 4.5.0 works fine with it.

**Comment by rbri** [comment]
Yes that is a new problem because 2.0.3 uses the spread syntax at one place

line 1464

    function restorePreservedElements() {
        const pantry = find('#--htmx-preserve-pantry--')
        if (pantry) {
            for (const preservedElt of [...pantry.children]) {
                const existingElement = find('#' + preservedElt.id)
                // @ts-ignore - use proposed moveBefore feature
                existingElement.parentNode.moveBefore(preservedElt, existingElement)
                existingElement.remove()
            }
            pantry.remove()
        }
    }

**Comment by rbri** [comment]
time flies - sorry for the late answer

Support for the spread operator in htmx scripts is now handled by org.htmlunit.javascript.preprocessor.HtmxTwoZeroSevenScriptPreProcessor. Please use this preprocessor to enable compatibility with Rhino.
You can use the latest 2.17.0-SNAPSHOT - it contains the new PreProzessor.

**Comment by mzeijen** [comment]
Seems that with this preprocessor the issue is fixed and I can test pages that use the latest HTMX 2.0.7.

Thank you very much!

**Comment by wleese** [comment]
When will this be available in a release?

**Comment by rbri** [comment]
the plan is to release this the next weekend - ok for you?

**Comment by wleese** [comment]
Awesome, thanks!
