### ISSUE TITLE
Problem with chartjs

### ISSUE THREAD

**Issue by huyit88** [HtmlUnit/htmlunit#98]
Hi Team,
I got the problem with chartjs.
final HtmlPage page = webClient.getPage(url);
webClient.waitForBackgroundJavaScript(4000);

Window window = page.getEnclosingWindow().getScriptableObject();
int i = 0;
do {
    System.out.println("start animation " + i);
    i = window.animateAnimationsFrames();
    System.out.println("end animation");
} while (i > 0);

HtmlCanvas pic = (HtmlCanvas) page.getElementById("canvas");
HTMLCanvasElement picelem = (HTMLCanvasElement) pic.getScriptableObject();

String png = picelem.toDataURL("image/png");
------------------------------------ERROR
Caused by: java.lang.NumberFormatException: For input string: "1)"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at com.gargoylesoftware.htmlunit.javascript.host.canvas.rendering.AwtRenderingBackend.setStrokeStyle(AwtRenderingBackend.java:339)
	at com.gargoylesoftware.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.setStrokeStyle(CanvasRenderingContext2D.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:188)

**Comment by huyit88** [comment]
@gredler @mguillem @asbjornu

**Comment by huyit88** [comment]
@rbri

**Comment by asbjornu** [comment]
Sorry, I'm not actively working on this project anymore.
